    Calculation of Paid Spread per Tradeи https://app.clickup.com/t/869bpwb2b
    Нужно подготовить отчет по сумме уплаченного спреда по сделкам, с учетом нашего спреда (маркапа).
    На staging-сервере будет предоставлена таблица сделок (SQL). Для каждой транзакции фиксируются поля:
    marketAsk, marketBid — “чистые” котировки от провайдера на момент сделки
    marketSpread — спред провайдера
    markup — рассчитанный маркап на момент сделки
    Требование:
    Добавить в выборку/таблицу вычисляемое поле: spread_with_markup_usd — уплаченный спред с маркапом, выраженный в USD.
    Примечания / упрощение:
    Для конвертации в USD можно использовать текущий курс (на момент формирования отчета), без исторических курсов.
    Ожидаемый результат:
    в таблицу сделок добаить колонку  spread_with_markup_usd по  каждой сделке

In [1]:
# --- SETTINGS ---

# Скрипт работает в двух режимах: тестовом и реальном.
IS_TEST_MODE = True  # Смени на False для работы с реальными данными

# ====================== BOOTSTRAP ======================
import os
import sys
from pathlib import Path

file_dir = os.getcwd()                                                  # */[sub_project_dir]/ipynb_files/...
#sub_project_dir = Path(file_dir).parent
#project_dir = sub_project_dir.parent
parent_dir = Path(file_dir).parent.parent.parent   # Поднимемся на 3 уровня выше, чтобы попасть в корень проекта

libraries_path = str(parent_dir / "libraries_py")
if libraries_path not in sys.path: sys.path.insert(0, libraries_path)

# ====================== ОСНОВНОЙ КОД ======================
from project_config import ProjectConfig

paths = ProjectConfig(file_dir=file_dir)

print(f"✅ Режим тестирования: {'ВКЛЮЧЕН' if IS_TEST_MODE else 'ВЫКЛЮЧЕН'}")
print(f"✅ Путь к файлу: {paths.input_samples_data}")
"""# Пример использования
print(paths.input_log_data)
print(paths.output_log_data)
print(paths.project_dir)"""

Заведомо существующие директории:
    📁 [file_dir]; Путь к директории с ipynb/py файлами: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\ipynb_files
    📁 [sub_project_dir]; Путь к директории СубПроекта: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade
    📁 [project_dir]; Путь к директории Проекта: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform
    📁 [parent_dir]; Путь к директории для доступа к библиотекам: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations

Директории СубПроекта:
  Директории Исходных Данных:
❗📁 [input_log_data] создан: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\input_data\input_log_data
❗📁 [input_temp_data] создан: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\input_data\input_temp_data
❗📁 [input_samples_data] создан: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\input_data\input_samples
 Директории Данных полученных в процессе работы скрипта:
❗📁 [output_log_data] создан: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\output_data\output_log_data
❗📁 [output_temp_data] создан: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\output_data\output_temp_data
    📁 [directory_data_set]; Путь к каталогу с Файлами Постоянных Конфигураций: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\data_set

✅ Каталог c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\libraries_py уже присутствует в sys.path
✅ Режим тестирования: ВКЛЮЧЕН
✅ Путь к файлу: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\input_data\input_samples

'# Пример использования\nprint(paths.input_log_data)\nprint(paths.output_log_data)\nprint(paths.project_dir)'

In [2]:
# Динамический импорт и инициализация библиотек и путей для работы с данными в Python <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
from pathlib import Path
import pandas as pd
import sys
import os
import numpy as np
from pathlib import Path
import io

# Динамически импорт необходимых функций <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
file_imports = "dynamic_import_functions.py"                                    # Библиотека для динамического импорта
file_imports_path = os.path.join(libraries_path, file_imports)
if os.path.exists(file_imports_path):
    import importlib
    importlib.invalidate_caches()                                               # Сбрасываем кэш перед импортом
    from dynamic_import_functions import import_functions, print_import_function_info
    print(f"\n ✅ Импорт [{file_imports}] успешен.")
else:
    print(f"\n ERROR: Файл '{file_imports}' не найден по пути {file_imports_path}, импорт не выполнен.\n")

modules_to_import = {                                                           # Формируем словарь, с именами файлов и функциями в них
    "yar_sed_general_lib":
        [libraries_path,
                "pd_set_option",                        # Вывод ДФ
                #"df_to_csv",                            # Сохранение ДФ в CSV 
                "CSVLoader",
                "save_data_log_work_file",
                #"detect_encoding",
                #"time_to_minutes",
                #"load_string_list",
                "list_print",
                "move_column",
                #"time_str_to_unix_time_2",
                "list_to_str",
                #'save_dict_log_work_file',
                'save_int_list_data_log_work_file',
                #'select_non_numeric_rows',
                'merge_left_with_check'],           # Вызываем функцию слияния ДФ с проверкой наличия колонок и размерности
    "sql_request_2":
        [libraries_path, 
                "pd_read_sql"]
                }

imported = import_functions(modules_to_import)          # Импортируем модули из словаря modules_to_import

print_import_function_info(modules_to_import, imported) # Выводим переменные ожидаемые импортированными функциями

 ✅ Импорт [dynamic_import_functions.py] успешен.
Импорт из 'yar_sed_general_lib' успешен: ['pd_set_option', 'CSVLoader', 'save_data_log_work_file', 'list_print', 'move_column', 'list_to_str', 'save_int_list_data_log_work_file', 'merge_left_with_check']
Импорт из 'sql_request_2' успешен: ['pd_read_sql']

 Импортированные функции и их параметры:
Функция 'pd_set_option' из модуля 'yar_sed_general_lib' ожидает параметры: name_df: str, df: pandas.core.frame.DataFrame, rows: int = 10, columns: int | None = None, min_rows: int | None = None, width: int = 100
Функция 'CSVLoader' из модуля 'yar_sed_general_lib' ожидает параметры: file_path, delimiter=';', encoding='utf-8', df_name='dataframe'
Функция 'save_data_log_work_file' из модуля 'yar_sed_general_lib' ожидает параметры: df, file_name, directory_data_temp_files, directory_data_log_files
Функция 'list_print' из модуля 'yar_sed_general_lib' ожидает параметры: lst, label=None, limit=10
Функция 'move_column' из модуля 'yar_sed_general_lib' ожидает параметры: df, list_col_name, add_list_col_name=False, new_position=0, new_position_step=1, print_info=False
Функция 'list_to_str' из модуля 'yar_sed_general_lib' ожидает параметры: list_to_str, quotes=False
Функция 'save_int_list_data_log_work_file' из модуля 'yar_sed_general_lib' ожидает параметры: int_list, file_name, directory_data_temp_files, directory_data_log_files
Функция 'merge_left_with_check' из модуля 'yar_sed_general_lib' ожидает параметры: df_left, df_right, left_on, right_on, cols_map
Функция 'pd_read_sql' из модуля 'sql_request_2' ожидает параметры: query, file_relative_path, levels_up, params=None

# Динамический импорт и инициализация библиотек и путей для работы с данными в Python <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
from pathlib import Path
import pandas as pd
import sys
import os
import numpy as np
from pathlib import Path
import io

file_dir = os.getcwd()                                                              # Определяем путь к текущему файлу (где выполняется код)
print(f"Файл в директории:                                      {file_dir}")

project_dir                     = Path(file_dir).parent                             # Переход на уровень выше (fc_to_mt5_migrations/own_platform)
print(f"Рабочая директория проекта:                             {project_dir}")

parent_dir                      = Path.cwd().parent.parent                          # Переход на уровень выше (fc_to_mt5_migrations)
print(f"Рабочая директория проекта для доступа к библиотекам:   {parent_dir}")

directory_data_log_files        = os.path.join(project_dir, 'log_data_files')
print(f"[directory_data_log_files];     Путь к каталогу с лог-файлами:                          {directory_data_log_files}")

directory_data_temp_files       = os.path.join(project_dir, 'working_data_files') 
print(f"[directory_data_temp_files];    Путь к каталогу с временными файлами:                   {directory_data_temp_files}")

directory_data_original_data    = os.path.join(project_dir, 'original_data')        # Путь к каталогу с оригинальными данными
print(f"Путь к каталогу с оригинальными данными:                {directory_data_original_data}")

directory_data_set              = os.path.join(project_dir, 'data_set')             # Путь к каталогу с конфигурационными данными
print(f"Путь к каталогу с файлами настроек:                     {directory_data_set}")

directory_data_output           = os.path.join(parent_dir, 'output_data')           # Путь к каталогу с выходными данными

libraries_path = os.path.join(parent_dir, "libraries_py")                           # Формируем путь к libraries_py каталогу с библиотеками *.py
sys.path.append(libraries_path)                                                     # sys.path — это список путей, где Python ищет модули при import module_name.

directory_data_set  = os.path.join(project_dir, 'data_set')     # Путь к каталогу с конфигурационными данными
print(f"[directory_data_set]; Путь к каталогу с файлами настроек:              {directory_data_set}")

directory_data_set_log  = os.path.join(project_dir, 'data_set', "log")     # Путь к каталогу с конфигурационными данными
print(f"[directory_data_set_log]; Путь к каталогу с ИСТОРИЕЙ файлов настроек: {directory_data_set_log}")

if libraries_path in sys.path: print(f"✅ Каталог {libraries_path} успешно добавлен в sys.path")
else: print(f"❌ Ошибка: {libraries_path} не найден в sys.path")

# Динамически импорт необходимых функций <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
file_imports = "dynamic_import_functions.py"                                    # Библиотека для динамического импорта
file_imports_path = os.path.join(libraries_path, file_imports)
if os.path.exists(file_imports_path):
    import importlib
    importlib.invalidate_caches()                                               # Сбрасываем кэш перед импортом
    from dynamic_import_functions import import_functions, print_import_function_info
    print(f"\n ✅ Импорт [{file_imports}] успешен.")
else:
    print(f"\n ERROR: Файл '{file_imports}' не найден по пути {file_imports_path}, импорт не выполнен.\n")

modules_to_import = {                                                           # Формируем словарь, с именами файлов и функциями в них
    "yar_sed_general_lib":
        [libraries_path,
                "pd_set_option",                        # Вывод ДФ
                #"df_to_csv",                            # Сохранение ДФ в CSV 
                "CSVLoader",
                "save_data_log_work_file",
                #"detect_encoding",
                #"time_to_minutes",
                #"load_string_list",
                "list_print",
                "move_column",
                #"time_str_to_unix_time_2",
                "list_to_str",
                #'save_dict_log_work_file',
                'save_int_list_data_log_work_file',
                #'select_non_numeric_rows',
                'merge_left_with_check'],           # Вызываем функцию слияния ДФ с проверкой наличия колонок и размерности
    "sql_request_2":
        [libraries_path, 
                "pd_read_sql"]
                }

imported = import_functions(modules_to_import)          # Импортируем модули из словаря modules_to_import

print_import_function_info(modules_to_import, imported) # Выводим переменные ожидаемые импортированными функциями

file_relative_path = "own_platform\\credits\\own_platforn_sql_main_stage_01.txt"  # Файл в корне проекта
levels_up = 1

sql_tab = f"SELECT * FROM `symbols` where tradeMode = 4"                                                                     # таблица глобальных настроек символов
symbols_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)
symbols_id_list = symbols_df['symbolId'].tolist()                                               # Колонка → список (включая NaN)
symbols_id_str = imported['list_to_str'] (symbols_id_list, quotes=True)
print(f"Список symbolId для фильтрации: {symbols_id_str}")

"""sql_tab = f"SELECT * FROM main.transactionsNativeEngineProd"                                                       # таблица сделок
trades_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)"""

# ВАРИАНТ №2: Загрузка данных SQL таблиц <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
file_relative_path = "own_platform\\credits\\own_platforn_sql_main_main_01.txt"  # Файл в корне проекта
levels_up = 1

accounts_groups_list = [
    'real/nativetradeengine/bvision/migration/usd',
    'real/nativetradeengine/dotbig/basic/usd',
    'real/nativetradeengine/dotbig/standard/usd',
    'real/nativetradeengine/dotbig/silver/usd',
    'real/nativetradeengine/dotbig/gold/usd',
    'real/nativetradeengine/dotbig/platinum/usd',
    'real/nativetradeengine/dotbig/vip/usd',
    'real/nativetradeengine/dotbig/elite/usd'
]
in_clause = ", ".join(f"'{item}'" for item in accounts_groups_list)                         # Формируем строку для SQL IN CLAUSE    
sql_tab = f"""SELECT * FROM `accountsGroups` WHERE name IN ({in_clause})""" # Запрос — только нужные строки!                                              
accounts_groups_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)  #accounts_groups_sql_tab = "SELECT * FROM `accountsGroups`"   # таблица групп счетов
accounts_groups_id_list = accounts_groups_df['id'].tolist()

sql_tab = f"SELECT * FROM `symbols` where tradeMode = 4"                                                                     # таблица глобальных настроек символов
symbols_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)
symbols_id_list = symbols_df['symbolId'].tolist()                                               # Колонка → список (включая NaN)
symbols_id_str = imported['list_to_str'] (symbols_id_list, quotes=True)
print(f"Список symbolId для фильтрации: {symbols_id_str}")

s_list = list(symbols_df ['name'].unique())
imported['save_int_list_data_log_work_file'](s_list, "symbols_names_list.txt", directory_data_temp_files, directory_data_log_files)

in_clause = ", ".join(f"'{item}'" for item in accounts_groups_id_list)
sql_tab  = f"SELECT * FROM `symbolsGroups` where symbolId in ({symbols_id_str}) and groupId in ({in_clause})"                                                       # таблица принадлежности символов группам символов
symbols_groups_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)

sql_tab = 'SELECT * FROM main.symbolsMarkets'                                                           # соответствие символов и рынков
symbols_markets_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)

sql_tab = f"SELECT * FROM main.trades where isClosed = 1"                                                       # таблица сделок
trades_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)

imported["pd_set_option"] ("[ trades_df ]",  trades_df, 5)
# натянуть данные из таблицы торговых условий. Сопоставить по symbolId и groupId нужные спреды

In [ ]:
# ====================== ЧТЕНИЕ SQL ФАЙЛА И ПРЕОБРАЗОВАНИЕ В DATAFRAME ======================

if IS_TEST_MODE:
    print(f"✅ Режим тестирования: ВКЛЮЧЕН. Используем тестовые данные из {paths.input_samples_data}")
    sql_file = Path(paths.input_samples_data, "transactions.sql")    # Путь к файлу
else:
    print(f"✅ Режим тестирования: ВЫКЛЮЧЕН. Используем реальные данные из {paths.input_temp_data}")
    sql_file = Path(paths.input_temp_data, "transactions.sql")        # Путь к файлу

sql_text = sql_file.read_text(encoding="utf-8")                                                                                 # 1. Читаем весь текст
values_text = sql_text.split("VALUES", 1)[1].strip().rstrip(";")                    # 2. Оставляем только VALUES (всё после первой скобки)
values_text = values_text.replace("),\n(", ")\n(").replace("),(", ")\n(")           # 3. Преобразуем в CSV-подобный формат; Заменяем "),(" на ")\n(" для разделения строк
lines = [line.strip("()") for line in values_text.splitlines()]                     # 4. Убираем внешние скобки каждой строки

df = pd.read_csv(io.StringIO("\n".join(lines)), header=None, quotechar="'", escapechar="\\")    # 5. Создаём DataFrame; Разделитель - запятая, но учтём кавычки
                 
columns = [                                                                                     # 6. Задаём имена колонок (взяли из INSERT)
    'id', 'timestamp', 'login', 'orderId', 'action', 'entry', 'reason', 'contractSize',
    'time', 'timeMsc', 'symbol', 'price', 'profit', 'swap', 'commission', 'margin',
    'positionId', 'comment', 'stopLoss', 'takeProfit', 'marketBid', 'marketAsk',
    'volume', 'volumeClosed', 'digits', 'marketSpread', 'markup', 'tickTimestampMsc',
    'spreadType', 'spreadAlgorithm'
]

df.columns = columns

df['symbol'] = df['symbol'].str.replace(r'^\s*["\']|["\']\s*$', '', regex=True)
numeric_cols = [                                                                        # Cписок колонок с числами в строковом формате
    'markup', 'marketSpread', 'action', 'entry', 'price', 'profit', 'swap', 'marketBid', 'marketAsk', 'volume', 'volumeClosed', 'contractSize']
for col in numeric_cols: df[col] = pd.to_numeric(df[col].str.strip(), errors='coerce')  # Преобразуем строки в float, убираем лишние пробелы

symbols = set(df['entry'])
print(symbols)

df = df[df['entry'] == 1].copy()                # Фильтруем только сделки ЗАКРЫТИЯ позиций/ т.к. нам не принципиально какой спред брать
df['spread_calc'] = np.where(df['action'] > 0,  # 
                                        (df['marketAsk'] + (df['price'] - df['marketAsk'])) - (df['marketBid'] - (df['price'] - df['marketAsk'])),
                                        (df['marketAsk'] + (df['marketBid'] - df['price'])) - (df['marketBid'] - (df['marketBid'] - df['price']))
                                    )
df['marketSpread'] = df['marketAsk'] - df['marketBid']
df['spread_check'] = df['spread_calc'] / df['marketSpread']
df = df.sort_values(by='spread_check', ascending=False)

# Перемещение колонок <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<                                        
new_columns_list = ['symbol', 'spread_check', 'spread_calc', 'marketSpread', 'price', 'marketBid', 'marketAsk'] # список колонок
df = imported['move_column'](df, new_columns_list,  new_position_step=1, add_list_col_name = False) # Перемещаем колонки / Добавляем новые колонки,

df_filter = df[abs(df['spread_check']) > 10].copy()
symbol_set = set(df_filter['symbol'])
imported['list_print'](list(symbol_set),  "Символы с аномальным спредом")
imported["pd_set_option"] ("[ df_filter ]",  df_filter, 5)

list_traders_df = df.copy()
imported["pd_set_option"] ("[ list_traders_df ]",  list_traders_df, 5)

✅ Режим тестирования: ВКЛЮЧЕН. Используем тестовые данные из c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\input_data\input_samples

{0.0, 1.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}

 [dif] Функция добавления новых колонок с пустыми значениями и изменения положения этих колонок
 list_col_name = ['symbol', 'spread_check', 'spread_calc', 'marketSpread', 'price', 'marketBid', 'marketAsk'];
 new_position = 0, new_position_step = 1
📝 [ 31 ] элементов в списке [ Символы с аномальным спредом ] список: ['USDJPY', 'SP500', 'SSPG.L', 'EURCHF', 'COPN.S', 'USDCAD', 'BRTSPOT', 'XAUUSD', 'USDRUB', 'AUDTRL']...

[ df_filter ]  (285 строк × 32 колонок)

,symbol,spread_check,spread_calc,marketSpread,price,marketBid,marketAsk,id,timestamp,login,orderId,action,entry,reason,contractSize,time,timeMsc,profit,swap,commission,margin,positionId,comment,stopLoss,takeProfit,volume,volumeClosed,digits,markup,tickTimestampMsc,spreadType,spreadAlgorithm
1292,FCHI,1098.288889,1482.69,1.35,7375.86,8116.53,8117.88,1074189,1765903751951,266972,0,0.0,1.0,1,100.0,'2025-12-16 16:49:12',1765903751951,-5641.80,-550.0,0.00000000,163.71000000,396657,'',0.00000000,0.00000000,0.07,0.07,2,0.675,1765903751837,'dynamic','percent'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14951,FCHI,-1398.000000,-1537.80,1.10,7346.75,8115.10,8116.20,1082188,1767181689158,307478,0,1.0,1.0,1,100.0,'2025-12-31 11:48:09',1767181689158,-60.32,0.0,0.00000000,86.49000000,426601,'',0.00000000,0.00000000,0.04,0.04,2,0.550,1767181688968,'dynamic','percent'

[ list_traders_df ]  (7,842 строк × 32 колонок)

,symbol,spread_check,spread_calc,marketSpread,price,marketBid,marketAsk,id,timestamp,login,orderId,action,entry,reason,contractSize,time,timeMsc,profit,swap,commission,margin,positionId,comment,stopLoss,takeProfit,volume,volumeClosed,digits,markup,tickTimestampMsc,spreadType,spreadAlgorithm
1292,FCHI,1098.288889,1482.69,1.35,7375.86,8116.53,8117.88,1074189,1765903751951,266972,0,0.0,1.0,1,100.0,'2025-12-16 16:49:12',1765903751951,-5641.80,-550.0,0.00000000,163.71000000,396657,'',0.00000000,0.00000000,0.07,0.07,2,0.675,1765903751837,'dynamic','percent'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14951,FCHI,-1398.000000,-1537.80,1.10,7346.75,8115.10,8116.20,1082188,1767181689158,307478,0,1.0,1.0,1,100.0,'2025-12-31 11:48:09',1767181689158,-60.32,0.0,0.00000000,86.49000000,426601,'',0.00000000,0.00000000,0.04,0.04,2,0.550,1767181688968,'dynamic','percent'

In [13]:
# Загрузка файла с торговыми условиями по торговым инструментам <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# Данные формируются в файле trading_conditions.ipynb в блоке # Фильтруем ДФ с торговыми условиями '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
df = list_traders_df.copy()

files_name = "trading_settings_sales_basic_df.csv"
file_path_symbols = Path(paths.input_samples_data, files_name)   # Файл c торговыми условиями
print("trading_settings_sales_basic_df.csv:", file_path_symbols)
loader = imported["CSVLoader"](file_path_symbols, delimiter=',', encoding='utf-8', df_name='my_dataframe')  # CSVLoader для загрузки данных из файла
trading_settings_sales_basic_df = loader.load_data()
#imported["pd_set_option"] (f"Торговые условия из, загруженного выше, файла {files_name} [ trading_settings_sales_basic_df ]",  trading_settings_sales_basic_df, 5)

cols_map = {"client_spread_money_lot": "spread_money_lot", "point_money":"point_money_", "precision_s":"precision_s_", "contractSize": "contractSize_"}
df, not_found, not_used = imported['merge_left_with_check']( # Вызываем функцию слияния ДФ с проверкой наличия колонок и размерности
    df_left= df, df_right= trading_settings_sales_basic_df, left_on= "symbol", right_on= "name_s",  cols_map=cols_map)

df['pos_price'] = df['volume'] * df['spread_money_lot']

df['spread_calc_point'] = df['spread_calc'] * (10** df['precision_s_'])

df['pos_price_2'] = pd.to_numeric(df['spread_calc_point'] * df['point_money_']) * df['contractSize'] * df['volume']
df['pos_price_2'] = df['pos_price_2'].map('{:.5f}'.format)
df['pos_price_3'] = (df['markup'] + df['marketSpread']) * (10** df['precision_s_']) * df['volume'] * df['point_money_'] * df['contractSize_']

df['point_money_'] = df['point_money_'].map('{:.5f}'.format)

"""# Перемещение колонок <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<                                        
new_columns_list = ['spread_calc','spread_calc_point','point_money_', 'pos_price', 'pos_price_2'] # список колонок
df = imported['move_column'](df, new_columns_list,  new_position_step=1, add_list_col_name = False) # Перемещаем колонки / Добавляем новые колонки,"""


list_col_name = ['markup','marketSpread','pos_price_3', 'contractSize_', 'contractSize', 'volume', 'spread_calc','spread_calc_point', 'pos_price_2', 'point_money_', 'spread_money_lot', 'pos_price']
df = imported["move_column"](df, list_col_name).copy()

df_filter = df[df['name_s'] == 'EURUSD'].copy()
imported["pd_set_option"] ("[ df_filter ]",  df_filter, 10)

imported["save_data_log_work_file"](df, "report_df.csv", paths.output_temp_data, paths.output_log_data)
print("Сумма уплаченного спреда", df['pos_price_3'].sum())
imported["pd_set_option"] ("[ df ]",  df, 100)

trading_settings_sales_basic_df.csv: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\input_data\input_samples\trading_settings_sales_basic_df.csv
✅ Success: [class CSVLoader]: DataFrame 'my_dataframe' успешно создан из 'c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\input_data\input_samples\trading_settings_sales_basic_df.csv'.

 [dif] Функция слияния ДФ с проверкой наличия колонок и размерности: merge_left_with_check()

 [dif] Функция добавления новых колонок с пустыми значениями и изменения положения этих колонок
 list_col_name = ['markup', 'marketSpread', 'pos_price_3', 'contractSize_', 'contractSize', 'volume', 'spread_calc', 'spread_calc_point', 'pos_price_2', 'point_money_', 'spread_money_lot', 'pos_price'];
 new_position = 0, new_position_step = 1

[ df_filter ]  (367 строк × 41 колонок)

,markup,marketSpread,pos_price_3,contractSize_,contractSize,volume,spread_calc,spread_calc_point,pos_price_2,point_money_,spread_money_lot,pos_price,symbol,spread_check,price,marketBid,marketAsk,id,timestamp,login,orderId,action,entry,reason,time,timeMsc,profit,swap,commission,margin,positionId,comment,stopLoss,takeProfit,volumeClosed,digits,tickTimestampMsc,spreadType,spreadAlgorithm,name_s,precision_s_
317,0.00005,0.00010,61.50,100000.0,100000.0,4.10,0.00042,42.0,172.20000,0.00001,54.6,223.860,EURUSD,4.200000,1.17440,1.17456,1.17466,1071153,1765463042593,261961,0,0.0,1.0,3,'2025-12-11 14:24:03',1765463042593,1459.60,0.00,0.00000000,1199.96000000,395450,'',0.00000000,1.17440000,4.10,5,1765463042221,'dynamic','percent',EURUSD,5.0
355,0.00005,0.00012,1.19,100000.0,100000.0,0.07,0.00044,44.0,3.08000,0.00001,54.6,3.822,EURUSD,3.666667,1.16608,1.16624,1.16636,1070171,1765393210528,308576,0,0.0,1.0,3,'2025-12-10 19:00:11',1765393210528,7.14,0.00,0.00000000,20.39000000,421980,'',0.00000000,1.16608000,0.07,5,1765393210260,'dynamic','percent',EURUSD,5.0
401,0.00005,0.00010,7.50,100000.0,100000.0,0.50,0.00034,34.0,17.00000,0.00001,54.6,27.300,EURUSD,3.400000,1.17500,1.17512,1.17522,1071341,1765467735464,302632,0,0.0,1.0,3,'2025-12-11 15:42:15',1765467735464,684.00,0.00,0.00000000,145.15000000,402996,'',0.00000000,1.17500000,0.50,5,1765467735009,'dynamic','percent',EURUSD,5.0
402,0.00005,0.00010,0.15,100000.0,100000.0,0.01,0.00034,34.0,0.34000,0.00001,54.6,0.546,EURUSD,3.400000,1.17500,1.17512,1.17522,1071340,1765467735464,653343,0,0.0,1.0,3,'2025-12-11 15:42:15',1765467735464,13.51,-1.60,0.00000000,2.88000000,411965,'',0.00000000,1.17500000,0.01,5,1765467735009,'dynamic','percent',EURUSD,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7579,0.00005,0.00013,0.36,100000.0,100000.0,0.02,0.00019,19.0,0.38000,0.00001,54.6,1.092,EURUSD,1.461538,1.18000,1.18003,1.18016,1079390,1766567829652,270330,0,0.0,1.0,3,'2025-12-24 09:17:10',1766567829652,1.58,0.00,0.00000000,5.90000000,426246,'',0.00000000,1.18000000,0.02,5,1766567828978,'dynamic','percent',EURUSD,5.0
7580,0.00005,0.00013,0.18,100000.0,100000.0,0.01,0.00019,19.0,0.19000,0.00001,54.6,0.546,EURUSD,1.461538,1.18000,1.18003,1.18016,1078564,1766492886847,297371,0,0.0,1.0,3,'2025-12-23 12:28:07',1766492886847,1.62,0.00,0.00000000,2.95000000,425778,'',0.00000000,1.18000000,0.01,5,1766492886006,'dynamic','percent',EURUSD,5.0
7589,0.00002,0.00010,6.00,100000.0,100000.0,0.50,0.00014,14.0,7.00000,0.00001,54.6,27.300,EURUSD,1.400000,1.17450,1.17438,1.17448,1082025,1767128123048,662822,0,1.0,1.0,3,'2025-12-30 20:55:23',1767128123048,89.50,-30.98,0.00000000,147.26000000,425634,'',0.00000000,1.17450000,0.50,5,1767128122768,'dynamic','percent');,EURUSD,5.0
7594,0.00002,0.00010,4.80,100000.0,100000.0,0.40,0.00014,14.0,5.60000,0.00001,54.6,21.840,EURUSD,1.400000,1.17869,1.17871,1.17881,1080263,1766763294297,662822,0,0.0,1.0,1,'2025-12-26 15:34:54',1766763294297,18.00,-2.00,0.00000000,0.00000000,426423,'',0.00000000,1.18000000,0.40,5,1766763294097,'dynamic','percent',EURUSD,5.0

💾 Полный путь к сохраняемому файлу: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\output_data\output_temp_data\report_df.csv
💾 Полный путь к сохраняемому файлу: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\Calculation_of_Paid_Spread_per_Trade\output_data\output_log_data\2026-07-30 10-17-15.report_df.csv
Сумма уплаченного спреда 369787.11940160627

[ df ]  (7,842 строк × 41 колонок)

,markup,marketSpread,pos_price_3,contractSize_,contractSize,volume,spread_calc,spread_calc_point,pos_price_2,point_money_,spread_money_lot,pos_price,symbol,spread_check,price,marketBid,marketAsk,id,timestamp,login,orderId,action,entry,reason,time,timeMsc,profit,swap,commission,margin,positionId,comment,stopLoss,takeProfit,volumeClosed,digits,tickTimestampMsc,spreadType,spreadAlgorithm,name_s,precision_s_
0,0.67500,1.3500,16.431447,100.0,100.0,0.07,1482.69000,148269.0,12030.98405,0.01159,320.224856,22.415740,FCHI,1098.288889,7375.86000,8116.53000,8117.88000,1074189,1765903751951,266972,0,0.0,1.0,1,'2025-12-16 16:49:12',1765903751951,-5641.80,-550.00,0.00000000,163.71000000,396657,'',0.00000000,0.00000000,0.07,2,1765903751837,'dynamic','percent',FCHI,2.0
1,0.67500,1.3500,4.694699,100.0,100.0,0.02,1482.69000,148269.0,3437.42402,0.01159,320.224856,6.404497,FCHI,1098.288889,7379.61000,8120.28000,8121.63000,1079296,1766565100095,206039,0,0.0,1.0,5,'2025-12-24 08:31:40',1766565100095,-666.82,-750.00,0.00000000,44.53000000,421214,'',0.00000000,8300.00000000,0.02,2,1766565099352,'dynamic','percent',FCHI,2.0
2,0.67500,1.3500,4.694699,100.0,100.0,0.02,1482.69000,148269.0,3437.42402,0.01159,320.224856,6.404497,FCHI,1098.288889,7379.61000,8120.28000,8121.63000,1079300,1766565100130,206039,0,0.0,1.0,5,'2025-12-24 08:31:40',1766565100130,-538.10,-400.00,0.00000000,44.24000000,421563,'',0.00000000,8350.00000000,0.02,2,1766565099352,'dynamic','percent',FCHI,2.0
3,0.75000,1.5000,20.865330,100.0,100.0,0.08,1543.00000,154300.0,14308.97964,0.01159,320.224856,25.617989,FCHI,1028.666667,7344.15000,8114.90000,8116.40000,1082187,1767181682437,307478,0,0.0,1.0,1,'2025-12-31 11:48:02',1767181682437,-3018.87,-7000.00,0.00000000,178.29000000,421109,'',0.00000000,8300.00000000,0.08,2,1767181681000,'dynamic','percent',FCHI,2.0
4,0.67500,1.3500,23.473496,100.0,0.0,0.10,1282.69000,128269.0,0.00000,0.01159,320.224856,32.022486,FCHI,950.140741,7416.66000,8057.33000,8058.68000,1070724,1765446106783,187498,0,0.0,1.0,5,'2025-12-11 09:41:47',1765446106783,1972.84,-2601.00,0.00000000,202.85000000,350612,'',0.00000000,0.00000000,0.10,2,1765446105670,'dynamic','percent',FCHI,2.0
5,0.67500,1.3500,58.683741,100.0,100.0,0.25,882.69000,88269.0,25580.02519,0.01159,320.224856,80.056214,FCHI,653.844444,7669.26000,8109.93000,8111.28000,1068474,1765217060242,265357,0,0.0,1.0,1,'2025-12-08 18:04:20',1765217060242,292.41,0.00,0.00000000,556.44000000,421144,'',0.00000000,0.00000000,0.25,2,0,'dynamic','percent',FCHI,2.0
6,0.67500,1.3500,4.694699,100.0,0.0,0.02,882.69000,88269.0,0.00000,0.01159,320.224856,6.404497,FCHI,653.844444,7682.21000,8122.88000,8124.23000,1067151,1764945407610,269204,0,0.0,1.0,5,'2025-12-05 14:36:48',1764945407610,3516.24,-450.00,0.00000000,36.10000000,352157,'',0.00000000,0.00000000,0.02,2,1764945406344,'dynamic','percent',FCHI,2.0
7,0.67500,1.3500,140.840982,100.0,100.0,0.60,880.01000,88001.0,61205.66555,0.01159,320.224856,192.134920,FCHI,651.859259,7689.00000,8128.33000,8129.68000,1068681,1765268504417,269337,0,0.0,1.0,3,'2025-12-09 08:21:44',1765268504417,2045.51,0.00,0.00000000,1336.71000000,421074,'',0.00000000,7689.00000000,0.60,2,1765268504321,'dynamic','percent',FCHI,2.0
8,0.55000,1.1000,1.650000,100.0,100.0,0.01,602.20000,60220.0,602.20000,0.01000,141048.000000,1410.480000,DJI,547.454545,48842.10000,48540.45000,48541.55000,1081035,1767019777603,69806,0,1.0,1.0,1,'2025-12-29 14:49:38',1767019777603,158.80,0.00,0.00000000,490.01000000,426890,'',0.00000000,48.60000000,0.01,2,1767019777519,'dynamic','percent',DJI,2.0
9,0.55000,1.1000,1.650000,100.0,100.0,0.01,601.20000,60120.0,601.20000,0.01000,141048.000000,1410.480000,DJI,546.545455,48690.10000,48388.95000,48390.05000,1081745,1767105732123,69806,0,1.0,1.0,2,'2025-12-30 14:42:12',1767105732123,76.30,0.00,0.00000000,487.66000000,427220,'',48690.00000000,48250.00000000,0.01,2,1767105731706,'dynamic','percent',DJI,2.0
10,0.47600,0.0028,674.136421,100000.0,100000.0,1.00,1.52624,152624.0,2148.90136,0.00000,28.643037,28.643037,AUDRUB,545.085714,50.60000,51.36172,51.36452,1062115,1764577638781,301356,0,0.0,1.0,3,'2025-12-01 08:27:19',1764577638781,-776.43,-375.00,0.00000000,163.56000000,417711,'',0.00000000,50.60000000,1.00,5,1764577638407,'dynamic','percent',AUDRUB,5.0
11,0.67500,1.3500,93.893985,100.0,0.0,0.40,702.69000,70269.0,0.00000,0.01159,320.224856,128.089943,FCHI,520.511111,7761.96000,8112.63000,8113.98000,1062772,1764608777073,269285,0,0.0,1.0,1,'2025-12-01 17:06:17',1764608777073,23572.19,0.00,0.00000000,856.39000000,354160,'',0.00000000,0.00000000,0.40,2,0,'dynamic','percent',FCHI,2.0
12,0.67500,1.3500,93.893985,100.0,0.0,0.40,702.69000,70269.0,0.00000,0.01159,320.224856,128.089943,FCHI,520.511111,7762.46000,8113.13000,8114.48000,1062770,1764608754825,269285,0,0.0,1.0,1,'2025-12-01 17:05:55',1764608754825,23724.78,0.00,0.00000000,856.42000000,354162,'',0.00000000,0.00000000,0.40,2,0,'dynamic','percent',FCHI,2.0
13,0.47600,0.0028,53.930914,100000.0,100000.0,0.08,1.02224,102224.0,115.14273,0.00000,28.643037,2.291443,AUDRUB,365.085714,52.99730,53.50702,53.50982,1081685,1767102999818,307660,0,0.0,1.0,3,'2025-12-30 13:56:40',1767102999818,0.30,0.00,0.00000000,13.40000000,427366,'',0.00000000,52.99730000,0.08,5,1767102999134,'dynamic','percent',AUDRUB,5.0
14,0.47600,0.0027,673.995624,100000.0,100000.0,1.00,0.95170,95170.0,1339.96581,0.00000,28.643037,28.643037,AUDRUB,352.481481,50.38452,50.85902,50.86172,1067444,1764952490536,240868,0,0.0,1.0,5,'2025-12-05 16:34:51',1764952490536,-1254.57,-75.00,0.00000000,166.18000000,420677,'',0.00000000,0.00000000,1.00,5,1764952489251,'dynamic','percent',AUDRUB,5.0
15,0.45900,0.0027,1105.102205,100000.0,100000.0,1.70,0.94934,94934.0,2272.29311,0.00000,28.643037,48.693163,AUDRUB,351.607407,53.23500,53.70832,53.71102,1076123,1766130749042,265207,0,0.0,1.0,3,'2025-12-19 07:52:29',1766130749042,60.37,0.00,0.00000000,282.04000000,423800,'',0.00000000,53.23500000,1.70,5,1766130748410,'dynamic','percent',AUDRUB,5.0
16,0.08000,0.1570,0.237000,100.0,100.0,0.01,55.20100,55201.0,55.20100,0.00100,196.595004,1.965950,XAUUSD,351.598726,4222.00000,4249.52200,4249.67900,1062193,1764581033809,300597,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033809,14.26,-25.00,0.00000000,42.08000000,412468,'',0.00000000,4222.00000000,0.01,3,1764581033464,'dynamic','percent',XAUUSD,3.0
17,0.47600,0.0028,20.224093,100000.0,100000.0,0.03,0.95480,95480.0,40.32992,0.00000,28.643037,0.859291,AUDRUB,341.000000,53.52692,54.00292,54.00572,1071025,1765457441988,305866,0,0.0,1.0,1,'2025-12-11 12:50:42',1765457441988,73.96,0.00,0.00000000,4.96000000,421167,'',0.00000000,0.00000000,0.03,5,1765457441586,'dynamic','percent',AUDRUB,5.0
18,0.45900,0.0027,6.500601,100000.0,100000.0,0.01,0.92070,92070.0,12.96319,0.00000,28.643037,0.286430,AUDRUB,341.000000,51.96872,52.42772,52.43042,1078969,1766511002929,305954,0,0.0,1.0,1,'2025-12-23 17:30:03',1766511002929,-10.46,0.00,0.00000000,1.65000000,424279,'',0.00000000,54.00000000,0.01,5,1766511002168,'dynamic','percent',AUDRUB,5.0
19,4.69200,0.0276,664.505901,100000.0,100000.0,0.10,9.41160,941160.0,1325.12580,0.00000,28.643037,2.864304,AUDRUB,341.000000,47.56673,52.25873,52.28633,1075260,1766032651516,296917,0,0.0,1.0,5,'2025-12-18 04:37:32',1766032651516,-996.48,0.00,0.00000000,16.51000000,395332,'',0.00000000,0.00000000,0.10,5,1766032650953,'dynamic','percent',AUDRUB,5.0
20,0.47600,0.0028,6.741364,100000.0,100000.0,0.01,0.95480,95480.0,13.44331,0.00000,28.643037,0.286430,AUDRUB,341.000000,53.93062,54.40662,54.40942,1081351,1767073625999,299644,0,0.0,1.0,1,'2025-12-30 05:47:06',1767073625999,12.82,0.00,0.00000000,1.66000000,425515,'',0.00000000,0.00000000,0.01,5,1767073625460,'dynamic','percent',AUDRUB,5.0
21,0.47600,0.0028,337.068211,100000.0,100000.0,0.50,0.95480,95480.0,672.16526,0.00000,28.643037,14.321519,AUDRUB,341.000000,50.89632,51.37232,51.37512,1067090,1764943007512,265207,0,0.0,1.0,1,'2025-12-05 13:56:48',1764943007512,181.63,0.00,0.00000000,82.79000000,420110,'',0.00000000,51.61492000,0.50,5,0,'dynamic','percent',AUDRUB,5.0
22,0.47600,0.0028,337.068211,100000.0,100000.0,0.50,0.95480,95480.0,672.16526,0.00000,28.643037,14.321519,AUDRUB,341.000000,52.88612,52.40732,52.41012,1075080,1765990150489,301356,0,1.0,1.0,1,'2025-12-17 16:49:10',1765990150489,-2007.48,-1400.00,0.00000000,82.74000000,420036,'',0.00000000,0.00000000,0.50,5,1765990148218,'dynamic','percent',AUDRUB,5.0
23,0.47600,0.0028,6.741364,100000.0,100000.0,0.01,0.95480,95480.0,13.44331,0.00000,28.643037,0.286430,AUDRUB,341.000000,51.20042,51.67642,51.67922,1069597,1765355317200,299644,0,0.0,1.0,1,'2025-12-10 08:28:37',1765355317200,0.70,0.00,0.00000000,1.65000000,420018,'',0.00000000,0.00000000,0.01,5,0,'dynamic','percent',AUDRUB,5.0
24,0.47600,0.0028,6.741364,100000.0,100000.0,0.01,0.95480,95480.0,13.44331,0.00000,28.643037,0.286430,AUDRUB,341.000000,51.91132,52.38732,52.39012,1069712,1765365114163,299644,0,0.0,1.0,1,'2025-12-10 11:11:54',1765365114163,8.14,0.00,0.00000000,1.66000000,420782,'',0.00000000,0.00000000,0.01,5,0,'dynamic','percent',AUDRUB,5.0
25,0.47600,0.0028,20.224093,100000.0,100000.0,0.03,0.95020,95020.0,40.13562,0.00000,28.643037,0.859291,AUDRUB,339.357143,50.38452,50.85822,50.86102,1067454,1764952490612,240868,0,0.0,1.0,5,'2025-12-05 16:34:51',1764952490612,-37.58,0.00,0.00000000,4.99000000,420676,'',0.00000000,0.00000000,0.03,5,1764952489251,'dynamic','percent',AUDRUB,5.0
26,0.08000,0.1570,7.110000,100.0,100.0,0.30,52.20100,52201.0,1566.03000,0.00100,196.595004,58.978501,XAUUSD,332.490446,4223.50000,4249.52200,4249.67900,1062192,1764581033809,305906,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033809,63.21,0.00,0.00000000,0.00000000,417906,'',0.00000000,4223.50000000,0.30,3,1764581033464,'dynamic','percent',XAUUSD,3.0
27,0.08000,0.1600,9.600000,100.0,100.0,0.40,48.40000,48400.0,1936.00000,0.00100,196.595004,78.638002,XAUUSD,302.500000,4225.40000,4249.52000,4249.68000,1062185,1764581033795,305906,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033795,82.92,0.00,0.00000000,0.00000000,417904,'',0.00000000,4225.40000000,0.40,3,1764581033464,'dynamic','percent',XAUUSD,3.0
28,1.00000,2.0000,3.000000,100.0,100.0,0.01,604.00000,60400.0,604.00000,0.01000,141048.000000,1410.480000,DJI,302.000000,48933.87000,48630.87000,48632.87000,1080379,1766769876963,69806,0,1.0,1.0,1,'2025-12-26 17:24:37',1766769876963,3.97,0.00,0.00000000,489.38000000,426715,'',0.00000000,0.00000000,0.01,2,1766769876666,'dynamic','percent',DJI,2.0
29,0.08000,0.1600,1.440000,100.0,100.0,0.06,39.20000,39200.0,235.20000,0.00100,196.595004,11.795700,XAUUSD,245.000000,4230.00000,4249.52000,4249.68000,1062186,1764581033795,307171,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033795,168.53,-300.00,0.00000000,252.10000000,412365,'',0.00000000,4230.00000000,0.06,3,1764581033464,'dynamic','percent',XAUUSD,3.0
30,0.08000,0.1600,0.480000,100.0,100.0,0.02,33.20000,33200.0,66.40000,0.00100,196.595004,3.931900,XAUUSD,207.500000,4233.00000,4249.52000,4249.68000,1062184,1764581033795,248611,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033795,52.62,0.00,0.00000000,84.13000000,417831,'',0.00000000,4233.00000000,0.02,3,1764581033464,'dynamic','percent',XAUUSD,3.0
31,0.08000,0.1600,2.400000,100.0,100.0,0.10,19.20000,19200.0,192.00000,0.00100,196.595004,19.659500,XAUUSD,120.000000,4240.00000,4249.52000,4249.68000,1062187,1764581033795,297700,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033795,821.90,0.00,0.00000000,415.78000000,417175,'',0.00000000,4240.00000000,0.10,3,1764581033464,'dynamic','percent',XAUUSD,3.0
32,0.08000,0.1600,2.400000,100.0,100.0,0.10,19.20000,19200.0,192.00000,0.00100,196.595004,19.659500,XAUUSD,120.000000,4240.00000,4249.52000,4249.68000,1062190,1764581033796,242974,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033796,761.61,0.00,0.00000000,416.38000000,416887,'',0.00000000,4240.00000000,0.10,3,1764581033464,'dynamic','percent',XAUUSD,3.0
33,0.08000,0.1600,1.200000,100.0,100.0,0.05,19.20000,19200.0,96.00000,0.00100,196.595004,9.829750,XAUUSD,120.000000,4240.00000,4249.52000,4249.68000,1062189,1764581033795,74957,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033795,554.06,0.00,0.00000000,206.46000000,415933,'',0.00000000,4240.00000000,0.05,3,1764581033464,'dynamic','percent',XAUUSD,3.0
34,0.08000,0.1600,1.200000,100.0,100.0,0.05,19.20000,19200.0,96.00000,0.00100,196.595004,9.829750,XAUUSD,120.000000,4240.00000,4249.52000,4249.68000,1062183,1764581033795,300421,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033795,157.26,0.00,0.00000000,210.43000000,417830,'',0.00000000,4240.00000000,0.05,3,1764581033464,'dynamic','percent',XAUUSD,3.0
35,0.08000,0.1600,2.400000,100.0,100.0,0.10,19.20000,19200.0,192.00000,0.00100,196.595004,19.659500,XAUUSD,120.000000,4240.00000,4249.52000,4249.68000,1062182,1764581033795,264385,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033795,814.94,0.00,0.00000000,415.85000000,416693,'',0.00000000,4240.00000000,0.10,3,1764581033464,'dynamic','percent',XAUUSD,3.0
36,0.08000,0.1570,0.237000,100.0,100.0,0.01,17.20100,17201.0,17.20100,0.00100,196.595004,1.965950,XAUUSD,109.560510,4241.00000,4249.52200,4249.67900,1062194,1764581033817,300597,0,0.0,1.0,3,'2025-12-01 09:23:54',1764581033817,11.88,-25.00,0.00000000,42.29000000,412089,'',0.00000000,4241.00000000,0.01,3,1764581033464,'dynamic','percent',XAUUSD,3.0
37,0.00705,0.0136,0.206500,1000.0,1000.0,0.01,1.48020,14802.0,14.80200,0.00010,96.367740,0.963677,XAGUSD,108.838235,79.40000,80.13330,80.14690,1080629,1766962806512,248611,0,0.0,1.0,3,'2025-12-28 23:00:07',1766962806512,19.74,0.00,0.00000000,7.74000000,426778,'',0.00000000,79.40000000,0.01,4,1766962805965,'dynamic','percent',XAGUSD,4.0
38,2.35000,4.7000,7.050000,100.0,0.0,0.01,509.50000,5095.0,0.00000,0.10000,1680.119978,16.801200,Cocoa,108.404255,5660.30000,5912.70000,5917.40000,1075221,1766004880742,266972,0,0.0,1.0,5,'2025-12-17 20:54:41',1766004880742,-1889.70,-911.00,0.00000000,75.50000000,353274,'',0.00000000,0.00000000,0.01,1,1765996170244,'dynamic','percent',Cocoa,1.0
39,0.03300,0.0060,35.100000,1000.0,10000.0,0.90,0.57200,572.0,5148.00000,0.00100,81.766800,73.590120,NG,95.333333,4.65700,4.36800,4.37400,1070141,1765392029917,268477,0,1.0,1.0,1,'2025-12-10 18:40:30',1765392029917,6066.00,-100.00,0.00000000,239.90000000,420741,'',0.00000000,4.40000000,0.90,3,0,'dynamic','percent',NG,3.0
40,0.03300,0.0060,19.500000,1000.0,10000.0,0.50,0.57200,572.0,2860.00000,0.00100,81.766800,40.883400,NG,95.333333,5.00000,4.71100,4.71700,1068264,1765207902421,307478,0,1.0,1.0,1,'2025-12-08 15:31:42',1765207902421,310.00,0.00,0.00000000,126.55000000,420844,'',0.00000000,4.40000000,0.50,3,0,'dynamic','percent',NG,3.0
41,0.03300,0.0060,1.950000,1000.0,10000.0,0.05,0.57200,572.0,286.00000,0.00100,81.766800,4.088340,NG,95.333333,4.07000,3.78100,3.78700,1077984,1766425070964,306178,0,1.0,1.0,1,'2025-12-22 17:37:51',1766425070964,17.00,0.00,0.00000000,10.26000000,425088,'',0.00000000,3.60000000,0.05,3,1766425070435,'dynamic','percent',NG,3.0
42,0.03300,0.0060,19.500000,1000.0,10000.0,0.50,0.57200,572.0,2860.00000,0.00100,81.766800,40.883400,NG,95.333333,4.10200,3.81300,3.81900,1073780,1765888361121,306165,0,1.0,1.0,1,'2025-12-16 12:32:41',1765888361121,640.00,0.00,0.00000000,105.75000000,422894,'',0.00000000,0.00000000,0.50,3,1765888358825,'dynamic','percent',NG,3.0
43,0.03300,0.0060,7.800000,1000.0,10000.0,0.20,0.57200,572.0,1144.00000,0.00100,81.766800,16.353360,NG,95.333333,4.07800,3.78900,3.79500,1076014,1766083960985,305401,0,1.0,1.0,1,'2025-12-18 18:52:41',1766083960985,42.00,0.00,0.00000000,40.99000000,424228,'',0.00000000,0.00000000,0.20,3,1766083958837,'dynamic','percent',NG,3.0
44,0.03300,0.0060,39.000000,1000.0,10000.0,1.00,0.57200,572.0,5720.00000,0.00100,81.766800,81.766800,NG,95.333333,4.06600,3.77700,3.78300,1077977,1766424784477,296227,0,1.0,1.0,1,'2025-12-22 17:33:04',1766424784477,-700.00,0.00,0.00000000,199.80000000,425631,'',0.00000000,0.00000000,1.00,3,1766424782652,'dynamic','percent',NG,3.0
45,0.03300,0.0060,53.820000,1000.0,10000.0,1.38,0.57200,572.0,7893.60000,0.00100,81.766800,112.838184,NG,95.333333,4.16400,3.87500,3.88100,1073186,1765810624105,306667,0,1.0,1.0,1,'2025-12-15 14:57:04',1765810624105,386.40,250.00,0.00000000,289.25000000,422863,'',0.00000000,3.24700000,1.38,3,1765810623848,'dynamic','percent',NG,3.0
46,0.03300,0.0060,7.800000,1000.0,10000.0,0.20,0.57200,572.0,1144.00000,0.00100,81.766800,16.353360,NG,95.333333,4.32300,4.03400,4.04000,1079656,1766587130430,305401,0,1.0,1.0,1,'2025-12-24 14:38:50',1766587130430,-574.00,0.00,0.00000000,40.36000000,424662,'',0.00000000,0.00000000,0.20,3,1766587129854,'dynamic','percent',NG,3.0
47,0.03300,0.0060,0.390000,1000.0,10000.0,0.01,0.57200,572.0,57.20000,0.00100,81.766800,0.817668,NG,95.333333,4.18200,3.89300,3.89900,1073317,1765816106876,261932,0,1.0,1.0,1,'2025-12-15 16:28:27',1765816106876,10.30,0.00,0.00000000,2.14000000,422885,'',0.00000000,0.00000000,0.01,3,1765816106510,'dynamic','percent',NG,3.0
48,0.03300,0.0060,1.950000,1000.0,10000.0,0.05,0.57200,572.0,286.00000,0.00100,81.766800,4.088340,NG,95.333333,4.36300,4.07400,4.08000,1079666,1766587564805,69806,0,1.0,1.0,1,'2025-12-24 14:46:05',1766587564805,20.50,0.00,0.00000000,11.01000000,426156,'',0.00000000,3.07000000,0.05,3,1766587564586,'dynamic','percent',NG,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7793,0.02600,0.0520,19.500000,1000.0,1000.0,0.25,-1.82800,-1828.0,-457.00000,0.00100,2204.020069,551.005017,BRTSPOT,-35.153846,64.00000,63.06000,63.11200,1068079,1765200715784,257822,0,0.0,1.0,3,'2025-12-08 13:31:56',1765200715784,69.25,0.00,0.00000000,159.31000000,421012,'',0.00000000,64.00000000,0.25,3,1765200715596,'dynamic','percent',BRTSPOT,3.0
7794,0.02600,0.0520,5.460000,1000.0,1000.0,0.07,-1.86800,-1868.0,-130.76000,0.00100,2204.020069,154.281405,BRTSPOT,-35.923077,64.00000,63.04000,63.09200,1066206,1764863519620,307105,0,0.0,1.0,3,'2025-12-04 15:52:00',1764863519620,17.50,0.00,0.00000000,44.63000000,419469,'',0.00000000,64.00000000,0.07,3,1764863519406,'dynamic','percent',BRTSPOT,3.0
7795,0.02600,0.0520,0.780000,1000.0,1000.0,0.01,-1.89600,-1896.0,-18.96000,0.00100,2204.020069,22.040201,BRTSPOT,-36.461538,61.56100,60.58700,60.63900,1077435,1766396749766,307661,0,0.0,1.0,1,'2025-12-22 09:45:50',1766396749766,-30.06,0.00,0.00000000,6.46000000,413086,'',0.00000000,67.00000000,0.01,3,1766396748649,'dynamic','percent',BRTSPOT,3.0
7796,0.02600,0.0520,7.800000,1000.0,1000.0,0.10,-1.89600,-1896.0,-189.60000,0.00100,2204.020069,220.402007,BRTSPOT,-36.461538,60.15900,59.18500,59.23700,1073923,1765893925202,304300,0,0.0,1.0,1,'2025-12-16 14:05:25',1765893925202,-184.10,0.00,0.00000000,62.00000000,422504,'',0.00000000,0.00000000,0.10,3,1765893924545,'dynamic','percent',BRTSPOT,3.0
7797,0.02600,0.0520,46.800000,1000.0,0.0,0.60,-1.89600,-1896.0,-0.00000,0.00100,2204.020069,1322.412042,BRTSPOT,-36.461538,60.65900,59.68500,59.73700,1074901,1765985216329,255774,0,0.0,1.0,1,'2025-12-17 15:26:56',1765985216329,-6636.60,-3000.00,0.00000000,430.32000000,351737,'',0.00000000,0.00000000,0.60,3,1765985214525,'dynamic','percent',BRTSPOT,3.0
7798,0.02600,0.0520,31.200000,1000.0,1000.0,0.40,-1.89600,-1896.0,-758.40000,0.00100,2204.020069,881.608028,BRTSPOT,-36.461538,62.35500,61.38100,61.43300,1078836,1766503724635,239202,0,0.0,1.0,1,'2025-12-23 15:28:45',1766503724635,906.40,-250.00,0.00000000,240.36000000,423736,'',0.00000000,63.80000000,0.40,3,1766503724449,'dynamic','percent',BRTSPOT,3.0
7799,0.02600,0.0520,7.800000,1000.0,1000.0,0.10,-1.89600,-1896.0,-189.60000,0.00100,2204.020069,220.402007,BRTSPOT,-36.461538,60.49500,59.52100,59.57300,1074781,1765980947657,298029,0,0.0,1.0,1,'2025-12-17 14:15:48',1765980947657,-690.40,-1200.00,0.00000000,67.40000000,393057,'',0.00000000,0.00000000,0.10,3,1765980944773,'dynamic','percent',BRTSPOT,3.0