<span style="color: yellow; font-weight: bold; letter-spacing: 4px;">change_trading_conditions.ipynb</span>

Создание новых символов по словарю.

Нужно доработать, что бы посредством словаря так же задавать и Валюты

In [1]:
# Динамический импорт и инициализация библиотек и путей для работы с данными в Python <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
from pathlib import Path
import pandas as pd
import sys
import os
import numpy as np

file_dir = os.getcwd()                                                              # Определяем путь к текущему файлу (где выполняется код)
print(f"Файл в директории:                                      {file_dir}")

project_dir                     = Path(file_dir).parent                             # Переход на уровень выше (fc_to_mt5_migrations/own_platform)
print(f"Рабочая директория проекта:                             {project_dir}")

parent_dir                      = Path.cwd().parent.parent                          # Переход на уровень выше (fc_to_mt5_migrations)
print(f"Рабочая директория проекта для доступа к библиотекам:   {parent_dir}")

directory_data_log_files        = os.path.join(project_dir, 'log_data_files')
print(f"[directory_data_log_files];     Путь к каталогу с лог-файлами:                          {directory_data_log_files}")

directory_data_temp_files       = os.path.join(project_dir, 'working_data_files') 
print(f"[directory_data_temp_files];    Путь к каталогу с временными файлами:                   {directory_data_temp_files}")

directory_data_original_data    = os.path.join(project_dir, 'original_data')        # Путь к каталогу с оригинальными данными
print(f"Путь к каталогу с оригинальными данными:                {directory_data_original_data}")

directory_data_set              = os.path.join(project_dir, 'data_set')             # Путь к каталогу с конфигурационными данными
print(f"Путь к каталогу с файлами настроек:                     {directory_data_set}")

directory_data_output           = os.path.join(parent_dir, 'output_data')           # Путь к каталогу с выходными данными

libraries_path = os.path.join(parent_dir, "libraries_py")                           # Формируем путь к libraries_py каталогу с библиотеками *.py
sys.path.append(libraries_path)                                                     # sys.path — это список путей, где Python ищет модули при import module_name.

directory_data_set  = os.path.join(project_dir, 'data_set')     # Путь к каталогу с конфигурационными данными
print(f"[directory_data_set]; Путь к каталогу с файлами настроек:              {directory_data_set}")

directory_data_set_log  = os.path.join(project_dir, 'data_set', "log")     # Путь к каталогу с конфигурационными данными
print(f"[directory_data_set_log]; Путь к каталогу с ИСТОРИЕЙ файлов настроек: {directory_data_set_log}")

if libraries_path in sys.path: print(f"✅ Каталог {libraries_path} успешно добавлен в sys.path")
else: print(f"❌ Ошибка: {libraries_path} не найден в sys.path")

# Динамически импорт необходимых функций <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
file_imports = "dynamic_import_functions.py"                                    # Библиотека для динамического импорта
file_imports_path = os.path.join(libraries_path, file_imports)
if os.path.exists(file_imports_path):
    import importlib
    importlib.invalidate_caches()                                               # Сбрасываем кэш перед импортом
    from dynamic_import_functions import import_functions, print_import_function_info
    print(f"\n ✅ Импорт [{file_imports}] успешен.")
else:
    print(f"\n ERROR: Файл '{file_imports}' не найден по пути {file_imports_path}, импорт не выполнен.\n")

modules_to_import = {                                    # Формируем словарь, с именами файлов и функциями в них
    "yar_sed_general_lib":
        [libraries_path,
                "pd_set_option",                         # Вывод ДФ
                #"df_to_csv",                            # Сохранение ДФ в CSV 
                #"CSVLoader",
                "save_data_log_work_file",
                #"detect_encoding",
                #"time_to_minutes",
                #"load_string_list",
                #"list_print",
                #"move_column",
                #"time_str_to_unix_time_2",
                "list_to_str",
                #'save_dict_log_work_file',
                'save_int_list_data_log_work_file',
                #'select_non_numeric_rows',
                #'find_intersecting_lists'
                ],                                      # Функция для поиска пересекающихся списков
    "sql_request_2":
        [libraries_path, 
                "pd_read_sql",
                "get_sql_tab"]                          # Идентичная функция для получения SQL таблицы, но с возможностью указать разделитель
                }

imported = import_functions(modules_to_import)          # Импортируем модули из словаря modules_to_import

print_import_function_info(modules_to_import, imported) # Выводим переменные ожидаемые импортированными функциями

Файл в директории:                                      c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\ipynb_files
Рабочая директория проекта:                             c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform
Рабочая директория проекта для доступа к библиотекам:   c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations
[directory_data_log_files];     Путь к каталогу с лог-файлами:                          c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\log_data_files
[directory_data_temp_files];    Путь к каталогу с временными файлами:                   c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\working_data_files
Путь к каталогу с оригинальными данными:                c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\original_data
Путь к каталогу с файлами настроек:                     c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\data_set
[directory_data_set]; Путь к каталогу с файлами настроек:              c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\data_set
[directory_data_set_log]; Путь к каталогу с ИСТОРИЕЙ файлов настроек: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\data_set\log
✅ Каталог c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\libraries_py успешно добавлен в sys.path

 ✅ Импорт [dynamic_import_functions.py] успешен.
Импорт из 'yar_sed_general_lib' успешен: ['pd_set_option', 'save_data_log_work_file', 'list_to_str', 'save_int_list_data_log_work_file']
Импорт из 'sql_request_2' успешен: ['pd_read_sql', 'get_sql_tab']

 Импортированные функции и их параметры:
Функция 'pd_set_option' из модуля 'yar_sed_general_lib' ожидает параметры: name_df: str, df: pandas.core.frame.DataFrame, rows: int = 10, columns: int | None = None, min_rows: int | None = None, width: int = 100
Функция 'save_data_log_work_file' из модуля 'yar_sed_general_lib' ожидает параметры: df, file_name, directory_data_temp_files, directory_data_log_files
Функция 'list_to_str' из модуля 'yar_sed_general_lib' ожидает параметры: list_to_str, quotes=False
Функция 'save_int_list_data_log_work_file' из модуля 'yar_sed_general_lib' ожидает параметры: int_list, file_name, directory_data_temp_files, directory_data_log_files
Функция 'pd_read_sql' из модуля 'sql_request_2' ожидает параметры: query, file_relative_path, levels_up, params=None
Функция 'get_sql_tab' из модуля 'sql_request_2' ожидает параметры: symbols_sql_tab, file_relative_path, levels_up=1, sep=';'

In [ ]:
name_displayName_dict ={
                        "ADNOC.Distribution"    :("ADNOC Distribution",     r'STOCKS\CFDs - Stocks Mena\Abu Dubai\ADNOC.Distribution', ),
                        "ADNOC.Gas"             :("ADNOC Gas",              r'STOCKS\CFDs - Stocks Mena\Abu Dubai\ADNOC.Gas'),
                        "ADNOC.Drilling"        :("ADNOC Drilling",         r'STOCKS\CFDs - Stocks Mena\Abu Dubai\ADNOC.Drilling'),
                        "ADNOC.Logistics"       :("ADNOC Logistics",        r'STOCKS\CFDs - Stocks Mena\Abu Dubai\ADNOC.Logistics'),
                        "Fertiglobe.PLC"        :("Fertiglobe PLC",         r'STOCKS\CFDs - Stocks Mena\Abu Dubai\Fertiglobe.PLC'),
                        "Dana.Gas"              :("Dana Gas",               r'STOCKS\CFDs - Stocks Mena\Abu Dubai\Dana.Gas'),
                        "Emaar.Development"     :("Emaar Development",      r'STOCKS\CFDs - Stocks Mena\Dubai\Dubai.Development'),
                        "Dubai.Financial.Market":("Dubai Financial Market", r'STOCKS\CFDs - Stocks Mena\Dubai\Dubai.Financial.Market'),
                        "Union.Properties"      :("Union Properties",       r'STOCKS\CFDs - Stocks Mena\Dubai\Union.Properties'),
                        "Dubai.Investments"     :("Dubai Investments",      r'STOCKS\CFDs - Stocks Mena\Dubai\Dubai.Investments'),
                        "EMAAR.EC"              :("EMAAR EC",               r'STOCKS\CFDs - Stocks Mena\Saudi Arabia\EMAAR.EC'),
                        "Aldar.Properties"      :("Aldar Properties",       r'STOCKS\CFDs - Stocks Mena\Abu Dubai\Aldar.Properties'),
                        "DEYAAR"                :("DEYAAR",                 r'STOCKS\CFDs - Stocks Mena\Dubai\DEYAAR'),
                        }

In [2]:
# Пути к Кредам SQL серверв <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#dot_big_sql_main_cred= "own_platform\\credits\\own_platforn_sql_main_main_01.txt"           # Получаем Данные с ПРОД сервера
dot_big_sql_main_cred= "own_platform\\credits\\own_platforn_sql_main_stage_01.txt"
print(f"Путь к файлу с данными для подключения к SQL серверу: [ {dot_big_sql_main_cred} ]")

Путь к файлу с данными для подключения к SQL серверу: [ own_platform\credits\own_platforn_sql_main_stage_01.txt ]

In [4]:
# Запрос из `symbols` по ключам верхнего уровня словаря с новыми символами, логика предполагает, что инсрументы (как таковые) уже заведены в таблицы <<<<
# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#query = "SELECT * FROM `symbols` WHERE `name` IN ('" + "', '".join(name_displayName_dict.keys()) + "')"
query = "SELECT * FROM `symbols` WHERE `name` = 'AEDUSD'"
symbols_fo_change_df  = imported["get_sql_tab"]   (query,            dot_big_sql_main_cred)
imported['pd_set_option']("[symbols_fo_change_df] Данные по символам для изменения торговых условий", symbols_fo_change_df, 5)

получаем данные SELECT * FROM `symbols` WHERE `name` = 'AEDUSD'; из: 10.1.0.8 pma.y.d main_stage_01

[symbols_fo_change_df] Данные по символам для изменения торговых условий  (1 строк × 31 колонок)

,symbolId,name,hedgedMarginPercent,isGap,gapThresholdPercent,gapConfirmTicksCount,displayName,path,marketId,marginInitialBuy,marginInitialSell,precision,spread,source,baseCurrency,profitCurrency,tradeMode,calcMode,contractSize,volumeMax,volumeMin,volumeStep,volumeDefault,swapMode,swap3days,swapLong,swapShort,swapProfileId,markupEnabled,maxQuoteDelay,popularity
0,10829,AEDUSD,None,0,0.0,0,AEDUSD,,33,0.0,0.0,5,0.0,,AED,USD,4,0,0.0,10000.0,1.0,0.1,1.0,0.0,None,0.0,0.0,None,0,0,0.0

In [5]:
# Получение Данных по торговому инструменту которые берутся как исходные для новых инсрументов <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
symbol_donor = 'EURUSD'  # Символ-донор, от которого будем брать торговые условия для новых символов
query = f"SELECT * FROM `symbols` WHERE `name` =  '{symbol_donor}'"
symbol_donor_df  = imported["get_sql_tab"]   (query,            dot_big_sql_main_cred)
imported['pd_set_option']("[symbol_donor_df] Данные по символу-донору", symbol_donor_df, 5)

получаем данные SELECT * FROM `symbols` WHERE `name` =  'EURUSD'; из: 10.1.0.8 pma.y.d main_stage_01

[symbol_donor_df] Данные по символу-донору  (1 строк × 31 колонок)

,symbolId,name,hedgedMarginPercent,isGap,gapThresholdPercent,gapConfirmTicksCount,displayName,path,marketId,marginInitialBuy,marginInitialSell,precision,spread,source,baseCurrency,profitCurrency,tradeMode,calcMode,contractSize,volumeMax,volumeMin,volumeStep,volumeDefault,swapMode,swap3days,swapLong,swapShort,swapProfileId,markupEnabled,maxQuoteDelay,popularity
0,239,EURUSD,0.0,0,0.5,3,EUR / USD,FOREX\Fx Majors\EURUSD,3,0.0025,0.0025,5,0.0,,EUR,USD,4,0,100000.0,1000.0,0.01,0.01,1.0,6.0,3,0.0,0.0,None,0,420,10.0

In [7]:
# Имеем два ДФ идентичной структуры - [symbol_donor_df] - данные по символу-донору, который используется для получения торговых условий,
# которые будут применены к символам из [symbols_fo_change_df], для которых планируется изменение торговых условий.
# нужно в symbols_fo_change_df заменить значения по всем колонкам значениями из symbol_donor_df,
# кроме колонок, которые идентифицируют символы - name, displayName, path, symbolId:
symbols_fo_change_df.update(
    pd.concat([symbol_donor_df] * len(symbols_fo_change_df), ignore_index=True)
    .drop(columns=['name', 'displayName', 'path', 'symbolId']))
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

"""                                                                # по словаою заменить значение displayName	 на первое значение в кортедже
symbols_fo_change_df['displayName'] = symbols_fo_change_df['name'].map(lambda x: name_displayName_dict.get(x, (x, None))[0])
                                                                        # по словаою заменить значение path	 на второе значение в кортедже
symbols_fo_change_df['path'] = symbols_fo_change_df['name'].map(lambda x: name_displayName_dict.get(x, (None, x))[1])
symbols_fo_change_df['profitCurrency'] = "AED"                                              # Заменить все значения profitCurrency на "AED"
symbols_fo_change_df['baseCurrency'] = None                                                 # Заменить все значения baseCurrency на None
symbols_fo_change_df['marketId'] = 78                                                       # Заменить все значения marketId на 78"""

imported["save_data_log_work_file"](symbols_fo_change_df, "symbols_fo_change_df.csv", directory_data_temp_files, directory_data_log_files)
imported['pd_set_option']("[symbols_fo_change_df] Данные по символам для изменения торговых условий", symbols_fo_change_df, 50)

💾 Полный путь к сохраняемому файлу: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\working_data_files\symbols_fo_change_df.csv
💾 Полный путь к сохраняемому файлу: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\log_data_files\2026-05-20 15-40-47.symbols_fo_change_df.csv

[symbols_fo_change_df] Данные по символам для изменения торговых условий  (1 строк × 31 колонок)

,symbolId,name,hedgedMarginPercent,isGap,gapThresholdPercent,gapConfirmTicksCount,displayName,path,marketId,marginInitialBuy,marginInitialSell,precision,spread,source,baseCurrency,profitCurrency,tradeMode,calcMode,contractSize,volumeMax,volumeMin,volumeStep,volumeDefault,swapMode,swap3days,swapLong,swapShort,swapProfileId,markupEnabled,maxQuoteDelay,popularity
0,10829,AEDUSD,0.0,0,0.5,3,AEDUSD,,3,0.0025,0.0025,5,0.0,,EUR,USD,4,0,100000.0,1000.0,0.01,0.01,1.0,6.0,3,0.0,0.0,None,0,420,10.0

In [8]:
accounts_groups_list = [
    'real/nativetradeengine/bvision/migration/usd',
    'real/nativetradeengine/dotbig/basic/usd',
    'real/nativetradeengine/dotbig/standard/usd',
    'real/nativetradeengine/dotbig/silver/usd',
    'real/nativetradeengine/dotbig/gold/usd',
    'real/nativetradeengine/dotbig/platinum/usd',
    'real/nativetradeengine/dotbig/vip/usd',
    'real/nativetradeengine/dotbig/elite/usd'
]

In [9]:
# ВАРИАНТ №2: Загрузка данных SQL таблиц <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
file_relative_path = "own_platform\\credits\\own_platforn_sql_main_main_01.txt"    # PROD server  Файл для подключения к БД и выполнения SQL запроса
#file_relative_path = "own_platform\\credits\\own_platforn_sql_main_stage_01.txt"  # STAGE server Файл для подключения к БД и выполнения SQL запроса
levels_up = 1

in_clause = ", ".join(f"'{item}'" for item in accounts_groups_list)                         # Формируем строку для SQL IN CLAUSE    
sql_tab = f"""SELECT * FROM `accountsGroups` WHERE name IN ({in_clause})""" # Запрос — только нужные строки!                                              
accounts_groups_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)  #accounts_groups_sql_tab = "SELECT * FROM `accountsGroups`"   # таблица групп счетов
accounts_groups_id_list = accounts_groups_df['id'].tolist()


symbols_id_list = symbol_donor_df['symbolId'].tolist()                                               # Колонка → список (включая NaN)
symbols_id_str = imported['list_to_str'] (symbols_id_list, quotes=True)
print(f"Список symbolId для фильтрации: {symbols_id_str}")

#s_list = list(symbols_id_str ['name'].unique())

in_clause = ", ".join(f"'{item}'" for item in accounts_groups_id_list)
sql_tab  = f"SELECT * FROM `symbolsGroups` where symbolId in ({symbols_id_str}) and groupId in ({in_clause})"                                                       # таблица принадлежности символов группам символов
symbols_groups_donor_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)
imported['pd_set_option']("[symbols_groups_donor_df] Данные по принадлежности символов группам символов", symbols_groups_donor_df, 50)
   
"""sql_tab = "SELECT * FROM symbolsMarkets"                                                      # соответствие символов и рынков
symbols_markets_df = imported["pd_read_sql"](sql_tab  + """;""", file_relative_path, levels_up)
imported['pd_set_option']("[symbols_markets_df] Данные по соответствию символов и рынков", symbols_markets_df, 5)"""

# отфильтровываем группы настройки которых транслируются на все торговые группы клиентов<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
"""nativetradeengine_accounts_groups_df = accounts_groups_df[accounts_groups_df["name"].isin(accounts_groups_list)]    # Точное совпадение из списка
imported["pd_set_option"]("[nativetradeengine_accounts_groups_df] отфильтровываем группы настройки которых транслируются на все торговые группы клиентов", nativetradeengine_accounts_groups_df, 70)"""

получаем данные SELECT * FROM `accountsGroups` WHERE name IN ('real/nativetradeengine/bvision/migration/usd', 'real/nativetradeengine/dotbig/basic/usd', 'real/nativetradeengine/dotbig/standard/usd', 'real/nativetradeengine/dotbig/silver/usd', 'real/nativetradeengine/dotbig/gold/usd', 'real/nativetradeengine/dotbig/platinum/usd', 'real/nativetradeengine/dotbig/vip/usd', 'real/nativetradeengine/dotbig/elite/usd'); из: 10.0.0.8 pma.y.d main
Список symbolId для фильтрации: '239'
получаем данные SELECT * FROM `symbolsGroups` where symbolId in ('239') and groupId in ('66', '3', '288', '296', '304', '312', '320', '328'); из: 10.0.0.8 pma.y.d main

[symbols_groups_donor_df] Данные по принадлежности символов группам символов  (8 строк × 23 колонок)

,id,symbolId,groupId,hedgedMarginPercent,marginInitialBuy,marginInitialSell,spread,spreadDiff,spreadDiffPercent,markUpBid,markUpAsk,tradeMode,calcMode,volumeMax,volumeMin,volumeStep,contractSize,swapMode,swap3days,swapLong,swapShort,createdAt,updatedAt
0,18620168,239,3,0.0,0.0025,0.0025,0.0,0.0,0.500,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.1000,-0.0800,2025-09-04 00:08:47,2026-02-17 07:36:34
1,18611978,239,66,100.0,0.0025,0.0025,0.0,0.0,0.500,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,0.0000,0.0000,2025-09-04 00:06:39,2025-12-25 22:31:35
2,18685688,239,288,0.0,0.0025,0.0025,0.0,0.0,0.005,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0008,-0.0008,2025-09-04 00:18:17,2025-12-25 22:31:35
3,18693878,239,296,0.0,0.0025,0.0025,0.0,0.0,0.200,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0320,-0.0320,2025-09-04 00:18:57,2025-12-25 22:31:35
4,18702068,239,304,0.0,0.0025,0.0025,0.0,0.0,0.100,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0160,-0.0160,2025-09-04 00:19:56,2025-12-25 22:31:35
5,18710258,239,312,0.0,0.0025,0.0025,0.0,0.0,0.300,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0480,-0.0480,2025-09-04 00:20:29,2025-12-25 22:31:35
6,18718448,239,320,0.0,0.0025,0.0025,0.0,0.0,0.400,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0640,-0.0640,2025-09-04 00:21:06,2025-12-25 22:31:35
7,18726638,239,328,0.0,0.0025,0.0025,0.0,0.0,0.050,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0080,-0.0080,2025-09-04 00:21:40,2025-12-25 22:31:35

'nativetradeengine_accounts_groups_df = accounts_groups_df[accounts_groups_df["name"].isin(accounts_groups_list)]    # Точное совпадение из списка\nimported["pd_set_option"]("[nativetradeengine_accounts_groups_df] отфильтровываем группы настройки которых транслируются на все торговые группы клиентов", nativetradeengine_accounts_groups_df, 70)'

In [10]:
# создать ДФ настроек по клиентской группе берём symbols_groups_donor_df, и "размножаем" его под каждый новый символ.
# Берём symbols_groups_donor_df меняем symbolId на symbolId из symbols_fo_change_df, остальные данные оставляем неизменными.
# Мы получим ДФ с настройками групп символов для всех символов, для которых планируется изменение торговых условий.
# количество строк в итоговом ДF будет равняться произведением количесва строк в этих двух ДF
# ---------------------------------------------------------------------
# декартово произведение:
# каждая строка symbols_groups_donor_df
# копируется для каждого symbolId из symbols_fo_change_df
symbols_groups_result_df = (
    symbols_groups_donor_df.assign(_tmp=1)
    .merge(
        symbols_fo_change_df[['symbolId']].assign(_tmp=1),
        on='_tmp',
        suffixes=('', '_new')
    )
    .drop(columns=['_tmp', 'symbolId'])
    .rename(columns={'symbolId_new': 'symbolId'})
)
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

symbols_groups_result_df = symbols_groups_result_df[symbols_groups_donor_df.columns]    # опционально: порядок колонок как в исходном donor_df

"""symbols_groups_result_df['id'] = None                                                   # Заменить все значения baseCurrency на None
symbols_groups_result_df['createdAt'] = None
symbols_groups_result_df['updatedAt'] = None"""


imported['pd_set_option']("[symbols_groups_result_df] Данные по принадлежности символов группам символов", symbols_groups_result_df, 5)

[symbols_groups_result_df] Данные по принадлежности символов группам символов  (8 строк × 23 колонок)

,id,symbolId,groupId,hedgedMarginPercent,marginInitialBuy,marginInitialSell,spread,spreadDiff,spreadDiffPercent,markUpBid,markUpAsk,tradeMode,calcMode,volumeMax,volumeMin,volumeStep,contractSize,swapMode,swap3days,swapLong,swapShort,createdAt,updatedAt
0,18620168,10829,3,0.0,0.0025,0.0025,0.0,0.0,0.50,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.100,-0.080,2025-09-04 00:08:47,2026-02-17 07:36:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,18726638,10829,328,0.0,0.0025,0.0025,0.0,0.0,0.05,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.008,-0.008,2025-09-04 00:21:40,2025-12-25 22:31:35

In [11]:
# К symbols_groups_result_df добавляем колонку с названием группы счетов (name переименовать в groupName), для которой эти настройки будут применены, по id группы из accounts_groups_df (колонку не переносить)
symbols_groups_result_df = symbols_groups_result_df.merge(
    accounts_groups_df[['id', 'name']],
    left_on='groupId',
    right_on='id',
    how='left',
    suffixes=('', '_group')
).drop(columns=['id_group']).rename(columns={'name': 'groupName'})

# Добавить одну колонку с именем символа (name переименовать в symbolName) взять из symbols_fo_change_df по symbolId, для удобства и наглядности
symbols_groups_result_df = symbols_groups_result_df.merge(
    symbols_fo_change_df[['symbolId', 'name']],
    left_on='symbolId',
    right_on='symbolId',
    how='left',
    suffixes=('', '_symbol')
).rename(columns={'name': 'symbolName'})#drop(columns=['symbolId']).

# Перенести groupName	symbolName в начало ДФ для удобства
cols = symbols_groups_result_df.columns.tolist()
cols = ['groupName', 'symbolName'] + [col for col in cols if col not in ['groupName', 'symbolName']]

cols = symbols_groups_result_df.columns.tolist()
cols = ['id', 'createdAt', 'updatedAt', 'groupName', 'symbolName'] + [col for col in cols if col not in ['id', 'createdAt', 'updatedAt', 'groupName', 'symbolName']]

symbols_groups_result_df = symbols_groups_result_df[cols]

imported["save_data_log_work_file"](symbols_groups_result_df, "symbols_groups_result_df.csv", directory_data_temp_files, directory_data_log_files)
imported['pd_set_option']("[symbols_groups_result_df] Данные по принадлежности символов группам символов", symbols_groups_result_df, 10)

💾 Полный путь к сохраняемому файлу: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\working_data_files\symbols_groups_result_df.csv
💾 Полный путь к сохраняемому файлу: c:\unique_data\rep_fo_metatrader_server\fc_to_mt5_migrations\own_platform\log_data_files\2026-05-20 15-44-16.symbols_groups_result_df.csv

[symbols_groups_result_df] Данные по принадлежности символов группам символов  (8 строк × 25 колонок)

,id,createdAt,updatedAt,groupName,symbolName,symbolId,groupId,hedgedMarginPercent,marginInitialBuy,marginInitialSell,spread,spreadDiff,spreadDiffPercent,markUpBid,markUpAsk,tradeMode,calcMode,volumeMax,volumeMin,volumeStep,contractSize,swapMode,swap3days,swapLong,swapShort
0,18620168,2025-09-04 00:08:47,2026-02-17 07:36:34,real/nativetradeengine/dotbig/basic/usd,AEDUSD,10829,3,0.0,0.0025,0.0025,0.0,0.0,0.500,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.1000,-0.0800
1,18611978,2025-09-04 00:06:39,2025-12-25 22:31:35,real/nativetradeengine/bvision/migration/usd,AEDUSD,10829,66,100.0,0.0025,0.0025,0.0,0.0,0.500,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,0.0000,0.0000
2,18685688,2025-09-04 00:18:17,2025-12-25 22:31:35,real/nativetradeengine/dotbig/elite/usd,AEDUSD,10829,288,0.0,0.0025,0.0025,0.0,0.0,0.005,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0008,-0.0008
3,18693878,2025-09-04 00:18:57,2025-12-25 22:31:35,real/nativetradeengine/dotbig/gold/usd,AEDUSD,10829,296,0.0,0.0025,0.0025,0.0,0.0,0.200,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0320,-0.0320
4,18702068,2025-09-04 00:19:56,2025-12-25 22:31:35,real/nativetradeengine/dotbig/platinum/usd,AEDUSD,10829,304,0.0,0.0025,0.0025,0.0,0.0,0.100,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0160,-0.0160
5,18710258,2025-09-04 00:20:29,2025-12-25 22:31:35,real/nativetradeengine/dotbig/silver/usd,AEDUSD,10829,312,0.0,0.0025,0.0025,0.0,0.0,0.300,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0480,-0.0480
6,18718448,2025-09-04 00:21:06,2025-12-25 22:31:35,real/nativetradeengine/dotbig/standard/usd,AEDUSD,10829,320,0.0,0.0025,0.0025,0.0,0.0,0.400,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0640,-0.0640
7,18726638,2025-09-04 00:21:40,2025-12-25 22:31:35,real/nativetradeengine/dotbig/vip/usd,AEDUSD,10829,328,0.0,0.0025,0.0025,0.0,0.0,0.050,0.0,0.0,4,0,100000.0,0.01,0.01,None,6,None,-0.0080,-0.0080

In [ ]:
query = f"SELECT * FROM `symbolsSessions` WHERE `symbolId` =  1070"
symbols_sessions_df = imported["get_sql_tab"]   (query,    dot_big_sql_main_cred) 

symbols_sessions_df['open']    = 360
symbols_sessions_df['close']   = 660
#symbols_sessions_df['id'] = None


sessions_result_df = (
    symbols_sessions_df.assign(_tmp=1)
    .merge(
        symbols_fo_change_df[['symbolId']].assign(_tmp=1),
        on='_tmp',
        suffixes=('', '_new')
    )
    .drop(columns=['_tmp', 'symbolId'])
    .rename(columns={'symbolId_new': 'symbolId'})
)

# Добавить одну колонку с именем символа (name переименовать в symbolName) взять из symbols_fo_change_df по symbolId, для удобства и наглядности
sessions_result_df = sessions_result_df.merge(
    symbols_fo_change_df[['symbolId', 'name']],
    left_on='symbolId',
    right_on='symbolId',
    how='left',
    suffixes=('', '_symbol')
)#.drop(columns=['symbolId']).rename(columns={'name': 'symbolName'})

imported["save_data_log_work_file"](sessions_result_df, "sessions_result_df.csv", directory_data_temp_files, directory_data_log_files)
imported['pd_set_option']("[sessions_result_df] Данные по принадлежности символов группам символов", sessions_result_df, 50)