    Загрузка всех сделок из МТ
        Выделение Балансовых операций за вычетом реферальных
        Выделение реферальных операций
        Выделение торговых операций

    Сравнение Балансовых, реферальных, торговых операций на стороне MetaTrader 5 и CRM

In [1]:
import os
import sys
import importlib  # Добавляем импорт библиотеки для динамического импорта модулей
import pandas as pd
import datetime

import re
import numpy as np

import warnings
# Отключение предупреждения FutureWarning
warnings.simplefilter(action='ignore', category=FutureWarning)

# Функция для динамического импорта модулей <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
sys.path.append(os.path.abspath("c:/unique_data/rep_fo_metatrader_server"))
file_imports = "dynamic_import_functions.py"  # Файл с функциями для динамического импорта

if os.path.exists(file_imports):
    importlib.invalidate_caches()           # Сбрасываем кэш перед импортом
    from dynamic_import_functions import import_functions  # Импортируем только нужные функции
    print(f"Импорт [{file_imports}] успешен.")
else: print(f"ERROR: Файл '{file_imports}' не найден, импорт не выполнен.")
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

modules_to_import = {                                               # Словарь модулей для импорта
    "imports":
        ["c:/unique_data/rep_fo_metatrader_server",
                "pd_set_option",
                "mt5admin",
                "admin_connect",
                "admin_disconnect"],
    "yar_sed_general_lib":
        ["c:/unique_data/rep_fo_metatrader_server",
                "list_print",
                "int_list_to_csv_file",
                "load_account_list",
                "find_intersecting_lists"],
    "sed_array_lib":
        ["c:/unique_data/rep_fo_metatrader_server",
            "array_to_dataframe"]
                }
imported = import_functions(modules_to_import) # Импортируем модули из словаря modules_to_import

Импорт [dynamic_import_functions.py] успешен.
Импорт из 'imports' успешен: ['pd_set_option', 'mt5admin', 'admin_connect', 'admin_disconnect']
Импорт из 'yar_sed_general_lib' успешен: ['list_print', 'int_list_to_csv_file', 'load_account_list', 'find_intersecting_lists']
Импорт из 'sed_array_lib' успешен: ['array_to_dataframe']

In [2]:
# получить id CRM сделок к переоткрытию и проверить нет ли этих id уже на МТ5
account_id_list = imported["load_account_list"](r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250118\acc_list.csv")
imported["list_print"](account_id_list, "Счета к миграции")
admin =  imported["mt5admin"]()
admin_connect = imported["admin_connect"]()
if  admin_connect is not None:
    print("Подключен Администратор МТ5")
    deal_array = admin_connect.DealRequestByLoginsNumPy(account_id_list, 307718788, 1759407988)
    print(deal_array)
    mt5_deal_df = imported["array_to_dataframe"](deal_array)
    imported["admin_disconnect"]()
    del deal_array
else: print("Ошибка подключения")

imported["pd_set_option"]("Список всех сделок их МТ5", mt5_deal_df, 5)

Файл: C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250118\acc_list.csv; Длинна списка: 1548
[1548] элементов в списке [Счета к миграции] список: [262146, 262151, 73740, 229393, 237585, 237591, 237602, 163878, 229419, 237613, 221255, 262218, 237646, 237656, 237657, 114780, 237660, 237678, 65649, 237689, 262266, 73852, 237694, 90243, 262291, 262298, 262302, 237728, 262308, 262317, 262320, 237747, 237748, 262324, 237757, 262335, 237764, 262340, 180429, 237776, 237778, 237779, 237796, 237797, 262391, 262399, 262411, 237841, 262422, 262424, 196889, 237854, 147748, 237870, 237871, 237878, 237895, 237904, 262480, 262483, 262490, 82283, 180587, 237940, 262523, 262524, 57730, 74114, 262540, 262552, 164260, 262570, 262572, 238002, 238004, 246204, 238013, 254397, 262593, 254406, 262604, 262606, 254419, 238048, 238056, 238068, 205301, 238070, 262647, 238078, 262655, 254464, 238081, 238097, 262681, 115229, 139807, 115232, 238111, 238114, 41508, 254500, 238119, 238122, 254508, 221741, 238136, 238138, 262720, 238145, 238155, 238163, 238165, 238170, 238172, 238177, 254561, 238180, 238181, 238185, 238194, 238197, 262776, 238205, 238210, 238214, 262797, 262798, 41615, 230033, 230036, 238235, 238237, 238263, 238272, 246471, 238291, 262867, 262875, 238302, 262879, 238305, 262881, 238328, 262908, 238333, 238338, 238339, 238355, 262932, 238359, 238362, 238367, 262945, 262949, 238375, 238376, 262963, 254783, 148293, 262987, 254796, 131937, 74597, 263016, 213865, 197482, 238441, 238450, 238451, 50037, 238456, 263036, 148356, 238469, 238470, 254860, 238477, 238478, 263056, 238481, 263058, 238493, 238504, 230319, 263091, 263092, 74680, 238527, 254914, 263107, 238539, 263121, 238547, 254932, 263127, 238553, 238555, 238558, 58337, 263144, 230383, 238578, 197627, 238592, 263169, 238597, 246794, 132108, 238604, 238611, 238623, 263203, 107559, 238639, 255024, 140338, 263227, 246843, 173117, 255038, 238663, 263241, 214111, 263265, 238692, 263269, 263284, 255097, 189563, 263292, 238717, 263295, 238726, 238733, 238734, 263313, 238738, 255137, 263333, 263334, 263337, 230578, 263346, 263348, 230589, 255169, 238788, 263386, 263390, 238815, 263403, 238828, 140526, 263408, 83187, 263419, 238850, 263432, 238859, 263437, 263445, 255264, 156971, 255283, 263486, 140613, 255305, 238934, 238938, 116066, 238951, 238953, 263533, 263536, 50548, 263542, 238967, 238973, 238975, 263568, 255377, 263571, 230805, 238999, 263584, 189857, 263585, 263590, 263592, 263614, 239044, 214475, 263629, 239075, 263659, 263660, 255474, 132596, 255477, 255479, 263674, 239104, 67074, 140805, 263697, 239124, 255509, 75286, 255512, 239129, 173596, 124448, 263720, 255541, 263741, 263756, 230997, 239202, 263781, 206442, 157291, 239211, 239213, 239216, 239224, 263819, 75408, 59025, 132761, 239266, 239274, 222897, 59057, 239283, 263861, 263870, 263893, 239318, 255706, 263901, 214756, 50922, 255731, 165620, 239351, 91898, 255742, 255748, 263962, 255774, 263969, 231205, 239434, 239436, 264013, 223059, 157525, 198489, 239451, 255835, 67427, 116589, 264047, 239482, 255867, 239496, 255883, 264076, 264078, 239526, 264103, 239538, 264114, 223157, 83897, 264130, 239560, 255944, 255954, 264146, 264148, 264150, 255961, 239586, 26596, 239591, 83944, 100334, 215027, 165878, 215034, 239616, 264195, 256016, 239633, 264214, 256027, 116783, 239666, 51273, 239694, 239696, 247888, 84054, 239705, 223323, 247908, 247912, 256107, 239735, 239742, 239746, 166027, 247950, 264334, 256146, 247955, 264339, 264345, 239771, 247974, 239784, 239787, 256171, 256174, 239791, 247988, 239801, 59585, 264385, 264387, 248004, 264392, 264393, 239820, 248026, 256222, 198880, 248033, 248035, 239849, 264425, 256237, 264430, 239865, 239867, 248059, 92413, 264448, 248070, 264454, 264457, 215309, 264463, 248082, 256279, 248088, 248093, 264479, 248099, 190756, 133412, 256293, 264485, 108844, 239916, 248117, 264506, 256326, 239943, 248139, 256339, 256342, 264542, 264551, 264559, 248176, 199027, 248179, 248202, 264597, 264598, 264599, 264604, 264605, 264608, 256417, 248226, 264610, 256423, 207277, 264624, 223666, 231863, 199098, 264647, 231881, 248269, 240079, 264657, 215507, 248275, 264661, 256471, 248281, 256482, 248291, 248296, 248300, 256492, 264684, 264691, 264698, 240135, 248329, 264715, 248332, 264721, 264727, 264730, 264742, 248359, 59947, 248364, 248365, 150072, 109120, 248389, 264776, 264784, 264785, 248403, 264797, 264804, 199270, 248429, 248433, 264818, 248454, 264847, 264852, 248474, 133791, 68257, 264867, 248485, 232119, 264887, 264889, 264899, 232136, 248527, 248535, 207593, 248588, 199442, 240402, 60191, 248612, 248630, 248634, 60224, 265027, 265030, 265031, 240457, 265034, 248651, 248660, 248664, 248668, 248669, 265056, 248685, 215918, 248700, 125821, 240516, 134023, 248713, 265103, 265107, 265116, 240543, 265120, 265124, 60325, 248755, 76728, 248761, 265144, 265146, 248767, 265152, 265168, 240595, 240597, 248796, 232415, 240612, 240623, 265207, 248824, 240643, 240644, 240650, 191504, 240667, 199729, 265274, 248891, 265276, 248899, 265285, 240714, 248907, 240717, 248909, 265294, 265298, 76883, 265308, 216159, 265315, 265318, 240745, 248941, 265328, 216180, 240757, 248954, 265338, 240764, 265344, 216193, 248963, 265357, 175247, 240792, 240806, 240807, 265389, 265395, 249027, 240840, 265416, 240842, 240846, 265426, 77018, 232670, 265441, 240868, 265451, 150765, 265453, 240879, 265455, 240885, 265463, 240888, 240899, 249093, 265484, 265485, 265488, 240920, 249118, 240930, 240932, 265509, 77112, 240955, 240981, 249173, 265558, 167267, 216426, 265579, 265581, 241006, 150901, 241015, 265591, 241025, 93586, 109983, 265633, 134562, 60857, 249280, 265666, 265673, 265680, 101841, 241109, 265685, 249322, 249326, 151028, 265717, 265721, 249347, 134669, 265762, 249385, 69177, 265792, 233029, 257607, 265809, 257618, 265810, 85590, 257631, 265824, 265831, 265833, 257646, 257653, 142989, 93838, 241297, 265873, 151198, 69278, 257694, 93860, 102054, 183974, 265909, 265915, 265919, 265922, 257732, 44745, 265932, 257745, 265941, 265949, 110312, 257784, 265977, 257792, 265987, 61198, 233234, 233235, 233236, 233238, 184088, 241434, 233243, 233246, 233247, 257822, 266016, 257832, 159532, 266031, 102194, 233272, 233274, 110401, 241478, 266059, 257922, 266137, 69530, 233379, 135085, 257969, 266162, 77747, 257979, 266172, 257983, 85955, 258003, 258012, 266205, 258016, 258019, 266213, 233446, 258034, 233476, 241682, 241685, 266265, 217115, 266273, 266275, 94255, 266298, 233540, 233543, 241740, 110677, 110678, 241750, 241753, 258141, 258143, 192611, 45169, 184434, 266370, 266387, 241834, 233648, 266420, 233657, 233658, 143559, 266448, 200914, 241876, 233691, 233705, 241900, 69872, 241912, 192776, 233739, 266511, 258323, 258324, 266515, 53531, 241948, 258332, 258334, 258335, 233764, 258342, 266534, 233768, 266535, 241962, 241971, 86327, 151863, 241975, 241980, 241985, 233796, 127310, 135507, 266579, 242006, 184664, 233834, 242035, 242047, 242060, 242061, 242062, 266638, 242069, 242077, 266659, 242089, 242090, 233910, 151997, 242109, 242111, 258501, 111049, 143820, 233936, 266706, 266714, 266716, 242144, 233953, 266724, 242157, 266740, 70133, 233975, 266749, 233983, 258563, 242185, 233997, 258584, 242201, 217630, 242207, 242218, 258609, 234041, 258621, 266821, 242249, 209483, 242252, 70223, 242264, 234081, 234084, 135785, 242285, 266861, 258673, 266865, 135796, 234100, 242294, 266870, 242300, 111229, 266878, 266885, 266886, 266887, 242312, 242319, 234129, 234130, 234142, 217778, 234163, 144052, 234165, 78520, 225976, 242362, 94907, 266940, 266936, 234174, 266942, 225989, 266956, 242381, 234194, 217813, 193238, 242394, 242395, 266972, 242398, 266975, 242400, 127717, 234214, 242405, 266984, 94953, 242409, 266987, 242412, 242418, 70396, 86783, 242434, 234243, 234247, 242441, 242442, 234252, 242445, 267024, 226079, 242465, 144162, 234282, 267059, 209717, 62265, 242490, 234304, 242496, 86853, 242502, 258895, 242515, 267097, 267100, 242533, 267111, 234356, 258937, 267136, 267138, 234371, 45956, 86917, 242565, 242568, 242569, 267146, 242572, 242574, 234384, 234387, 267159, 242585, 267161, 37788, 242591, 242596, 160696, 234425, 259001, 267194, 267205, 234439, 267219, 234452, 234462, 267230, 267232, 267234, 242663, 242667, 234479, 259058, 242676, 242681, 242685, 242688, 234510, 87057, 234518, 234519, 234521, 160797, 242719, 242720, 259104, 242724, 201769, 259116, 242734, 267323, 78910, 218179, 234578, 267348, 242776, 267356, 70752, 226408, 242797, 242802, 267380, 242813, 234622, 234624, 242816, 193672, 267419, 242844, 234672, 242869, 259260, 193728, 87233, 267461, 210121, 267468, 201937, 234705, 242901, 234711, 267480, 234716, 242912, 259298, 242923, 242924, 128249, 234753, 267522, 267521, 234767, 267538, 267539, 79124, 267542, 259354, 267549, 242974, 62751, 95529, 226603, 70956, 267569, 242995, 259380, 234806, 259397, 234822, 243025, 234845, 243038, 267619, 234860, 71025, 87409, 234875, 243069, 234879, 234884, 243076, 267655, 259464, 226697, 243083, 234895, 259472, 234897, 267666, 259477, 243094, 267670, 267673, 267674, 243099, 243100, 243101, 259484, 234922, 218543, 243126, 267707, 243132, 120253, 234941, 243133, 79303, 259527, 267725, 259541, 259547, 234976, 259553, 161252, 177637, 226797, 243181, 161265, 243191, 267769, 267772, 71176, 235022, 259608, 136733, 259614, 235041, 243238, 243245, 103983, 243262, 235074, 243269, 235082, 243277, 267857, 243283, 243284, 235093, 235101, 63070, 259678, 259679, 267875, 235108, 235110, 243303, 259692, 259695, 243312, 235124, 235125, 243318, 243316, 235133, 153215, 235140, 243336, 235145, 259721, 226955, 267917, 267922, 259732, 243352, 243354, 259739, 259740, 145054, 235169, 235182, 259761, 54964, 235189, 243383, 235194, 227005, 267965, 243396, 243397, 112327, 95948, 259804, 243427, 235236, 259811, 136934, 235241, 243437, 161520, 112376, 186115, 63237, 259853, 243472, 259857, 87828, 243482, 235299, 243501, 243504, 243506, 137017, 243513, 243515, 243518, 235332, 137031, 243541, 218979, 243585, 235402, 235404, 235407, 235415, 243625, 104363, 210878, 202695, 243655, 243657, 169930, 243661, 161747, 243669, 235478, 243676, 243680, 243686, 210939, 55306, 243733, 104486, 243752, 210994, 235571, 211003, 235580, 235594, 235627, 227441, 235637, 235638, 235640, 235655, 235657, 71820, 235669, 260258, 71849, 235691, 235692, 260267, 186546, 260279, 235708, 235716, 71880, 260301, 235727, 235745, 112866, 145638, 260329, 71921, 260340, 260355, 260368, 260382, 219426, 203045, 260390, 260398, 194863, 227641, 55627, 235861, 235869, 219488, 235880, 104816, 235892, 211323, 145789, 63881, 235913, 260504, 80295, 260526, 260543, 235967, 260545, 235975, 235978, 235987, 260601, 236026, 236032, 260609, 236046, 236054, 260631, 55887, 260701, 80483, 260717, 260727, 227962, 203413, 236208, 219838, 80620, 211692, 203509, 236283, 187140, 203527, 236298, 236303, 236307, 236316, 203563, 260911, 178998, 260919, 260934, 244567, 195445, 138117, 236439, 236441, 56248, 89044, 261083, 236530, 261110, 80912, 236568, 56349, 236573, 146464, 261167, 72755, 236627, 154719, 187488, 187498, 244852, 261236, 236676, 261252, 244874, 244888, 195740, 154782, 244899, 228522, 261290, 163012, 261318, 122059, 220363, 244942, 97498, 204014, 64751, 236787, 236800, 261389, 236824, 236837, 236840, 236841, 236842, 212279, 261432, 236857, 228679, 187730, 212306, 236885, 236888, 114014, 261478, 261479, 261490, 236921, 236923, 212356, 236939, 236983, 261563, 236990, 261569, 261574, 237021, 237035, 261615, 138738, 237049, 237056, 261632, 237066, 81429, 237084, 220705, 130601, 237100, 261679, 237117, 237120, 147009, 237126, 237128, 261710, 228960, 261728, 261737, 220777, 261739, 261740, 106093, 261742, 237174, 237178, 261756, 237194, 229010, 261781, 237207, 237209, 237213, 56990, 171687, 237224, 237227, 163499, 237230, 261810, 237235, 237241, 237246, 237250, 237257, 237258, 261835, 261836, 237265, 237266, 237268, 229076, 89816, 237276, 237280, 237290, 237296, 237298, 229109, 237305, 237316, 261892, 261901, 237328, 261910, 261918, 237343, 237346, 261931, 261932, 237370, 89922, 139076, 171847, 261961, 237387, 261965, 261967, 261972, 229213, 237406, 73569, 237412, 237413, 57190, 261996, 261999, 262002, 262006, 262009, 229244, 237444, 73604, 237453, 262030, 262039, 81821, 262046, 237472, 237490, 262068, 237493, 237498, 262075, 245693, 262078, 212930, 262082, 262085, 90054, 237515, 262103, 237532, 237540, 262116, 221162, 73712, 262133, 237560, 237565]
import.py admin =  <MT5Manager.AdminAPI object at 0x0000018F8B028C00>
import.py admin =  <MT5Manager.AdminAPI object at 0x0000018F8C911680>
import.py MT5admin connect: True
Подключен Администратор МТ5
[(3436674, b'', 139807, 1100, 0, 2, 0, 2, 2,      0., 1688983353, b'', 0.     ,   0,  1.000000e+03, 0., 0., 0., 0.        , 0.     , 0,       0, b'#42623, balance, deposit', 0., 0.   ,   0, 0., 0., 0, 1688983353000, 2, b'', 0.,  32, 0., 0.,       0,       0, 0., 0., 0.     , 0.     , 0.)
 (3436675, b'',  37788, 1100, 0, 5, 0, 2, 2,      0., 1688995885, b'', 0.     ,   0,  2.341245e+06, 0., 0., 0., 0.        , 0.     , 0,       0, b'#42625, balance, correction', 0., 0.   ,   0, 0., 0., 0, 1688995885000, 2, b'', 0.,  32, 0., 0.,       0,       0, 0., 0., 0.     , 0.     , 0.)
 (3436694, b'',  90054,    0, 0, 0, 0, 5, 2, 100000., 1689000332, b'AUDCHF', 0.59111, 300,  0.000000e+00, 0., 0., 0., 1.09123845, 0.61471, 0, 4241640, b'#906, RP=1.13, SP=-3.38', 0., 0.   ,   0, 0., 0., 0, 1689000332337, 0, b'', 0., 256, 0., 0., 3000000,       0, 0., 0., 0.56264, 0.56374, 0.)
 ...
 (3709170, b'', 262078,    0, 0, 0, 1, 4, 2,  10000., 1736758617, b'Bitwise_LTD', 6.356  , 300,  0.000000e+00, 0., 0., 0., 1.        , 1.     , 0, 4327011, b'#200971, PC=0.0', 0., 6.356, 300, 0., 0., 0, 1736758617156, 0, b'', 0., 256, 0., 0., 3000000, 3000000, 0., 0., 7.2545 , 7.3178 , 0.)
 (3709171, b'', 267230, 1100, 0, 3, 0, 2, 2,      0., 1736886647, b'', 0.     ,   0, -5.000000e+01, 0., 0., 0., 0.        , 0.     , 0,       0, b'#61347, balance, credit', 0., 0.   ,   0, 0., 0., 0, 1736886647000, 2, b'', 0.,  32, 0., 0.,       0,       0, 0., 0., 0.     , 0.     , 0.)
 (3709172, b'', 263659, 1100, 0, 3, 0, 2, 2,      0., 1736936474, b'', 0.     ,   0, -2.590000e+02, 0., 0., 0., 0.        , 0.     , 0,       0, b'#61359, balance, credit', 0., 0.   ,   0, 0., 0., 0, 1736936474000, 2, b'', 0.,  32, 0., 0.,       0,       0, 0., 0., 0.     , 0.     , 0.)]
import.py admin.Disconnect() True
Список всех сделок их МТ5

,Deal (uint64),ExternalID (|S128),Login (uint64),Dealer (uint64),Order (uint64),Action (uint32),Entry (uint32),Digits (uint32),DigitsCurrency (uint32),ContractSize (float64),Time (int64),Symbol (|S128),Price (float64),Volume (uint64),Profit (float64),Storage (float64),Commission (float64),ObsoleteValue (float64),RateProfit (float64),RateMargin (float64),ExpertID (uint64),PositionID (uint64),Comment (|S128),ProfitRaw (float64),PricePosition (float64),VolumeClosed (uint64),TickValue (float64),TickSize (float64),Flags (uint64),TimeMsc (int64),Reason (uint32),Gateway (|S64),PriceGateway (float64),ModificationFlags (uint32),PriceSL (float64),PriceTP (float64),VolumeExt (uint64),VolumeClosedExt (uint64),Fee (float64),Value (float64),MarketBid (float64),MarketAsk (float64),MarketLast (float64)
0,3436674,b'',139807,1100,0,2,0,2,2,0.0,1688983353,b'',0.0,0,1000.0,0.0,0.0,0.0,0.0,0.0,0,0,"b'#42623, balance, deposit'",0.0,0.0,0,0.0,0.0,0,1688983353000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
1,3436675,b'',37788,1100,0,5,0,2,2,0.0,1688995885,b'',0.0,0,2341245.0,0.0,0.0,0.0,0.0,0.0,0,0,"b'#42625, balance, correction'",0.0,0.0,0,0.0,0.0,0,1688995885000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268707,3709171,b'',267230,1100,0,3,0,2,2,0.0,1736886647,b'',0.0,0,-50.0,0.0,0.0,0.0,0.0,0.0,0,0,"b'#61347, balance, credit'",0.0,0.0,0,0.0,0.0,0,1736886647000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
268708,3709172,b'',263659,1100,0,3,0,2,2,0.0,1736936474,b'',0.0,0,-259.0,0.0,0.0,0.0,0.0,0.0,0,0,"b'#61359, balance, credit'",0.0,0.0,0,0.0,0.0,0,1736936474000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#admin =  imported["mt5admin"]()
imported["admin_disconnect"]()

In [4]:
df = mt5_deal_df

# Преобразование байтовых строк в обычные строки
df['Comment (|S128)'] = df['Comment (|S128)'].apply(lambda x: x.decode('utf-8') if isinstance(x, bytes) else x)

# Функция для извлечения числа между # и ,
def extract_number(comment):
    match = re.search(r'#(\d+),', comment)
    return int(match.group(1)) if match else np.nan

# Функция для извлечения текста после числа
def extract_text(comment):
    match = re.search(r'#\d+,(.*)', comment)
    return match.group(1).strip() if match else np.nan

# Создание первого DataFrame, отфильтрованного по принципу: Action (uint32) = 0 или 1
df1 = df[df['Action (uint32)'].isin([0, 1])].copy()
df1['Number'] = df1['Comment (|S128)'].apply(extract_number)
df1['Text'] = df1['Comment (|S128)'].apply(extract_text)

# Создание второго DataFrame, отфильтрованного по принципу: Action (uint32) > 1
df2 = df[df['Action (uint32)'] > 1].copy()
df2['Number'] = df2['Comment (|S128)'].apply(extract_number)
df2['Text'] = df2['Comment (|S128)'].apply(extract_text)

df3 = df2[df2['Text'].str.contains('balance', case=False, na=False) & ~df2['Text'].str.contains('referrals', case=False, na=False)]
mt_balans_id_list = df3['Number'].dropna().astype(int).tolist()
print("\n", len(mt_balans_id_list), "mt_balans_id_list = ", "mt_balans_id_list")
file_path = r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\mt_balans_id_list.csv"
text = "БАЛАНСОВЫЕ операции на MT5:"
imported["int_list_to_csv_file"](mt_balans_id_list, file_path, text)
imported["list_print"](mt_balans_id_list, text)
imported["pd_set_option"](text, df3, 3)

df5 = df2[df2['Text'].str.contains('balance', case=False, na=False) & df2['Text'].str.contains('referrals', case=False, na=False)]
mt_referrals_id_list = df5['Number'].dropna().astype(int).tolist()
print("\n",len(mt_referrals_id_list), "mt_referrals_id_list = ", "mt_referrals_id_list")
file_path = r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\mt_referrals_id_list.csv"
text = "РЕФЕРАЛЬНЫЕ операции на МТ5:"
imported["int_list_to_csv_file"](mt_referrals_id_list, file_path, text)
imported["list_print"](mt_referrals_id_list, text)
imported["pd_set_option"](text, df5, 3)

df4 = df1[df1['Text'].str.contains('RP', case=False, na=False) & df1['Text'].str.contains('SP', case=False, na=False)]
mt_trade_id_list = df4['Number'].dropna().astype(int).tolist()
print("\n",len(mt_trade_id_list), "mt_trade_id_list = ", "mt_trade_id_list")
file_path = r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\mt_trade_id_list.csv"
text = "ТОРГОВЫЕ операции на МТ5:"
imported["int_list_to_csv_file"](mt_trade_id_list, file_path, text)
imported["list_print"](mt_trade_id_list, text)
imported["pd_set_option"](text, df4, 3)

 7990 mt_balans_id_list =  mt_balans_id_list
Путь к сохранённому списку [БАЛАНСОВЫЕ операции на MT5:]: [C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\mt_balans_id_list.csv]

,Deal (uint64),ExternalID (|S128),Login (uint64),Dealer (uint64),Order (uint64),Action (uint32),Entry (uint32),Digits (uint32),DigitsCurrency (uint32),ContractSize (float64),Time (int64),Symbol (|S128),Price (float64),Volume (uint64),Profit (float64),Storage (float64),Commission (float64),ObsoleteValue (float64),RateProfit (float64),RateMargin (float64),ExpertID (uint64),PositionID (uint64),Comment (|S128),ProfitRaw (float64),PricePosition (float64),VolumeClosed (uint64),TickValue (float64),TickSize (float64),Flags (uint64),TimeMsc (int64),Reason (uint32),Gateway (|S64),PriceGateway (float64),ModificationFlags (uint32),PriceSL (float64),PriceTP (float64),VolumeExt (uint64),VolumeClosedExt (uint64),Fee (float64),Value (float64),MarketBid (float64),MarketAsk (float64),MarketLast (float64),Number,Text
0,3436674,b'',139807,1100,0,2,0,2,2,0.0,1688983353,b'',0.0,0,1000.0,0.0,0.0,0.0,0.0,0.0,0,0,"#42623, balance, deposit",0.0,0.0,0,0.0,0.0,0,1688983353000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,42623,"balance, deposit"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268708,3709172,b'',263659,1100,0,3,0,2,2,0.0,1736936474,b'',0.0,0,-259.0,0.0,0.0,0.0,0.0,0.0,0,0,"#61359, balance, credit",0.0,0.0,0,0.0,0.0,0,1736936474000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,61359,"balance, credit"

 192 mt_referrals_id_list =  mt_referrals_id_list
Путь к сохранённому списку [РЕФЕРАЛЬНЫЕ операции на МТ5:]: [C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\mt_referrals_id_list.csv]
[192] элементов в списке [РЕФЕРАЛЬНЫЕ операции на МТ5:] список: [1, 2, 3, 5, 6, 7, 9, 8, 12, 13, 11, 15, 17, 22, 16, 19, 20, 21, 23, 24, 25, 27, 28, 35, 38, 31, 33, 34, 36, 39, 40, 41, 43, 44, 45, 46, 47, 49, 64, 50, 51, 52, 53, 54, 56, 57, 58, 59, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 92, 89, 91, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 90, 117, 129, 115, 116, 118, 119, 120, 121, 122, 123, 127, 128, 130, 131, 132, 133, 135, 136, 137, 138, 139, 141, 142, 143, 144, 145, 146, 147, 148, 149, 151, 152, 153, 154, 124, 125, 126, 140, 150, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 206, 207, 208, 202, 203, 204, 205]
РЕФЕРАЛЬНЫЕ операции на МТ5:

,Deal (uint64),ExternalID (|S128),Login (uint64),Dealer (uint64),Order (uint64),Action (uint32),Entry (uint32),Digits (uint32),DigitsCurrency (uint32),ContractSize (float64),Time (int64),Symbol (|S128),Price (float64),Volume (uint64),Profit (float64),Storage (float64),Commission (float64),ObsoleteValue (float64),RateProfit (float64),RateMargin (float64),ExpertID (uint64),PositionID (uint64),Comment (|S128),ProfitRaw (float64),PricePosition (float64),VolumeClosed (uint64),TickValue (float64),TickSize (float64),Flags (uint64),TimeMsc (int64),Reason (uint32),Gateway (|S64),PriceGateway (float64),ModificationFlags (uint32),PriceSL (float64),PriceTP (float64),VolumeExt (uint64),VolumeClosedExt (uint64),Fee (float64),Value (float64),MarketBid (float64),MarketAsk (float64),MarketLast (float64),Number,Text
7638,3441739,b'',127717,1100,0,5,0,2,2,0.0,1694706001,b'',0.0,0,195.00,0.0,0.0,0.0,0.0,0.0,0,0,"#1, balance, referrals",0.0,0.0,0,0.0,0.0,0,1694706001000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,1,"balance, referrals"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268632,3709096,b'',237728,1100,0,5,0,2,2,0.0,1736745695,b'',0.0,0,786.43,0.0,0.0,0.0,0.0,0.0,0,0,"#205, balance, referrals",0.0,0.0,0,0.0,0.0,0,1736745695000,2,b'',0.0,32,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,205,"balance, referrals"

 130263 mt_trade_id_list =  mt_trade_id_list
Путь к сохранённому списку [ТОРГОВЫЕ операции на МТ5:]: [C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\mt_trade_id_list.csv]

,Deal (uint64),ExternalID (|S128),Login (uint64),Dealer (uint64),Order (uint64),Action (uint32),Entry (uint32),Digits (uint32),DigitsCurrency (uint32),ContractSize (float64),Time (int64),Symbol (|S128),Price (float64),Volume (uint64),Profit (float64),Storage (float64),Commission (float64),ObsoleteValue (float64),RateProfit (float64),RateMargin (float64),ExpertID (uint64),PositionID (uint64),Comment (|S128),ProfitRaw (float64),PricePosition (float64),VolumeClosed (uint64),TickValue (float64),TickSize (float64),Flags (uint64),TimeMsc (int64),Reason (uint32),Gateway (|S64),PriceGateway (float64),ModificationFlags (uint32),PriceSL (float64),PriceTP (float64),VolumeExt (uint64),VolumeClosedExt (uint64),Fee (float64),Value (float64),MarketBid (float64),MarketAsk (float64),MarketLast (float64),Number,Text
2,3436694,b'',90054,0,0,0,0,5,2,100000.0,1689000332,b'AUDCHF',0.59111,300,0.0,0.0,0.0,0.0,1.091238,0.61471,0,4241640,"#906, RP=1.13, SP=-3.38",0.0,0.0,0,0.0,0.0,0,1689000332337,0,b'',0.0,256,0.0,0.0,3000000,0,0.0,0.0,0.56264,0.56374,0.0,906.0,"RP=1.13, SP=-3.38"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268705,3709169,b'',262078,0,0,1,0,4,2,10000.0,1736758366,b'Bitwise_LTD',6.35600,300,0.0,0.0,0.0,0.0,1.000000,1.00000,0,4327011,"#200971, RP=1.0, SP=0.0",0.0,0.0,0,0.0,0.0,0,1736758366086,0,b'',0.0,256,0.0,0.0,3000000,0,0.0,0.0,7.25450,7.31780,0.0,200971.0,"RP=1.0, SP=0.0"

In [5]:
crm_balans_id_list = imported["load_account_list"](r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250118\crm_balans_id_list_250118.csv")
imported["list_print"](crm_balans_id_list, "ID БАЛАНСОВЫХ операций в ЦРМ")

crm_referrals_id_list = imported["load_account_list"](r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250118\crm_referrals_id_list_250118.csv")
imported["list_print"](crm_referrals_id_list, "ID РЕФЕРАЛЬНЫХ операций в ЦРМ")

crm_statement_id_list = imported["load_account_list"](r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250118\crm_statement_id_list_250118.csv")
imported["list_print"](crm_statement_id_list, "ID ТОРГОВЫХ операций в ЦРМ")

Файл: C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250118\crm_balans_id_list_250118.csv; Длинна списка: 8158

In [7]:
dif_balans_id_list      = set(crm_balans_id_list)    - set(mt_balans_id_list)
text = "dif_balans_id_list"
imported["list_print"](dif_balans_id_list,  text)
file_path = r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\dif_balans_id_list.csv"
imported["int_list_to_csv_file"](dif_balans_id_list, file_path, text)

dif_referrals_id_list   = set(crm_referrals_id_list) - set(mt_referrals_id_list)
text = "dif_referrals_id_list"
imported["list_print"](dif_referrals_id_list,  text)
file_path = r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\dif_referrals_id_list.csv"
imported["int_list_to_csv_file"](dif_referrals_id_list, file_path, text)

dif_statement_id_list   = set(crm_statement_id_list) - set(mt_trade_id_list)
text = "dif_statement_id_list"
imported["list_print"](dif_statement_id_list,  text)
file_path = r"C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\dif_trade_id_list.csv"
imported["int_list_to_csv_file"](dif_statement_id_list, file_path, text)

[175] элементов в списке [dif_balans_id_list] список: {61440, 50177, 61442, 52227, 61443, 61445, 61446, 61447, 61448, 61449, 60938, 61451, 60940, 61454, 61456, 60461, 55854, 60466, 47679, 47168, 47169, 47681, 52800, 52802, 54338, 58945, 49225, 56411, 54883, 56419, 55403, 55405, 57966, 58478, 57968, 57973, 58487, 50302, 46724, 46725, 46726, 57501, 58543, 51907, 51911, 54983, 48338, 48855, 48856, 52456, 55535, 55536, 54009, 52483, 54024, 61225, 47938, 47939, 61250, 61252, 59718, 61256, 61259, 52044, 52045, 59726, 61263, 61264, 61265, 59730, 59732, 59734, 61270, 61275, 61276, 61280, 61281, 61283, 61285, 61286, 61292, 61295, 61296, 58737, 61300, 56181, 61305, 61307, 61311, 61312, 56193, 58242, 58245, 58246, 61318, 51593, 61321, 61324, 50062, 58254, 58255, 61326, 58260, 61342, 56735, 50594, 52130, 61346, 58789, 61351, 61352, 52137, 61355, 54188, 61364, 52151, 61368, 61369, 61370, 61371, 57276, 61376, 61377, 61378, 61379, 61380, 61381, 61382, 61383, 61385, 61386, 61390, 61391, 61392, 61393, 61394, 61395, 54229, 61397, 61399, 61400, 61401, 61402, 61403, 61404, 61405, 51678, 61406, 61408, 61409, 54754, 61411, 61412, 61413, 61414, 61415, 61416, 61418, 61419, 61422, 61423, 61425, 61426, 61427, 54260, 61428, 61429, 61431, 61433, 61434, 61435, 61436, 61437, 61438, 61439}
Путь к сохранённому списку [dif_balans_id_list]: [C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\dif_balans_id_list.csv]
[8] элементов в списке [dif_referrals_id_list] список: {209, 210, 211, 212, 213, 214, 215, 216}
Путь к сохранённому списку [dif_referrals_id_list]: [C:\unique_data\rep_fo_metatrader_server\files\migration_errors\migration_errors_250119\dif_referrals_id_list.csv]